import { axisBands, durationSegment, edgePath, eventSegments, nodeCenter, resolvedNodeRect } from './geometry';
import type { AtlasProject, NodeEntity } from '../model/project';

const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function shape(node:NodeEntity,rect:{x:number;y:number;width:number;height:number}):string{const{x,y,width:w,height:h}=rect,cx=x+w/2,cy=y+h/2,r=Math.min(w,h)/2;if(node.shape==='sphere'||node.shape==='circle')return `<circle cx="${cx}" cy="${cy}" r="${r}"/>`;if(node.shape==='diamond')return `<path d="M ${cx} ${y} L ${x+w} ${cy} L ${cx} ${y+h} L ${x} ${cy} Z"/>`;return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${node.shape==='pill'?h/2:node.shape==='rounded'?14:0}"/>`}

export function projectSvg(project:AtlasProject,includeReferences=false):string{
  const nodes=new Map(project.nodes.map(n=>[n.id,n]));
  const bandsX=axisBands(project.board.axes.x,60,project.board.width-120),bandsY=axisBands(project.board.axes.y,60,project.board.height-120);
  const gradients=project.edges.filter(e=>e.colors.length>1).map(e=>{const source=nodes.get(e.sourceId),target=nodes.get(e.targetId),a=source?nodeCenter(source,project):{x:0,y:0},b=target?nodeCenter(target,project):{x:1,y:0};return `<linearGradient id="gradient-${esc(e.id)}" gradientUnits="userSpaceOnUse" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}">${e.colors.map((color,index)=>`<stop offset="${index/Math.max(1,e.colors.length-1)*100}%" stop-color="${esc(color)}"/>`).join('')}</linearGradient>`}).join('');
  const markers=`<marker id="marker-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="context-stroke"/></marker><marker id="marker-circle" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="7" markerHeight="7"><circle cx="5" cy="5" r="4" fill="context-stroke"/></marker><marker id="marker-diamond" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M5 0L10 5L5 10L0 5Z" fill="context-stroke"/></marker><marker id="marker-bar" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="7" markerHeight="7"><path d="M5 0L5 10" stroke="context-stroke" stroke-width="2"/></marker>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${project.board.width}" height="${project.board.height}" viewBox="0 0 ${project.board.width} ${project.board.height}"><defs>${markers}${gradients}</defs><rect width="100%" height="100%" fill="${esc(project.board.background)}" fill-opacity="${project.board.backgroundOpacity}"/>
  ${bandsX.filter(b=>b.color!=='transparent'&&b.opacity>0).map(b=>`<rect x="${b.start}" y="0" width="${b.length}" height="${project.board.height}" fill="${esc(b.color)}" fill-opacity="${b.opacity}"/>`).join('')}
  ${bandsY.filter(b=>b.color!=='transparent'&&b.opacity>0).map(b=>`<rect x="0" y="${b.start}" width="${project.board.width}" height="${b.length}" fill="${esc(b.color)}" fill-opacity="${b.opacity}"/>`).join('')}
  ${includeReferences?project.references.filter(r=>r.visible).map(r=>`<image href="${esc(r.dataUrl)}" x="${r.x}" y="${r.y}" width="${r.width}" height="${r.height}" opacity="${r.opacity}" transform="rotate(${r.rotation} ${r.x+r.width/2} ${r.y+r.height/2})"/>`).join(''):''}
  ${project.areas.map(a=>`<g><rect x="${a.x}" y="${a.y}" width="${a.width}" height="${a.height}" rx="${a.radius}" fill="${a.fill}" fill-opacity="${a.fillOpacity}" stroke="${a.stroke}" stroke-width="${a.strokeWidth}"/>${a.showTitle!==false?`<text x="${a.x+12}" y="${a.y+(a.titleSize??16)+8}" fill="${esc(a.titleColor??a.stroke)}" font-family="Inter,Arial" font-size="${a.titleSize??16}" font-weight="700">${esc(a.name)}</text>`:''}</g>`).join('')}
  ${project.nodes.map(n=>{const s=durationSegment(n,project);return s?`<line x1="${s.x}" x2="${s.x}" y1="${s.y1}" y2="${s.y2}" stroke="${n.fill}" stroke-width="${s.width}" opacity="${n.opacity*.75}" stroke-linecap="round"/>`:''}).join('')}
  ${project.edges.map(e=>{const a=nodes.get(e.sourceId),b=nodes.get(e.targetId);return a&&b?`<path d="${edgePath(e,a,b,project)}" fill="none" stroke="${e.colors.length>1?`url(#gradient-${esc(e.id)})`:esc(e.color)}" stroke-width="${e.width}" stroke-dasharray="${esc(e.dash)}" stroke-linecap="${e.lineCap}" opacity="${e.opacity}"${e.startMarker!=='none'?` marker-start="url(#marker-${e.startMarker})"`:''}${e.endMarker!=='none'?` marker-end="url(#marker-${e.endMarker})"`:''}/>`:''}).join('')}
  ${project.events.map(e=>{const segments=eventSegments(e,project),first=segments[0];return `<g>${segments.map(s=>`<line x1="${s.x1}" x2="${s.x2}" y1="${s.y}" y2="${s.y}" stroke="${e.color}" stroke-width="${e.lineWidth}" stroke-dasharray="${esc(e.dash)}"/>`).join('')}<text x="${first.x1}" y="${first.y-10}" fill="${e.color}" font-family="Inter,Arial" font-size="16">${esc(e.title)}</text></g>`}).join('')}
  ${project.nodes.map(n=>{const r=resolvedNodeRect(n,project),cx=r.x+r.width/2,size=Math.min(r.width,r.height)*(n.containerVisible?.58:.9)*n.iconScale;return `<g fill="${n.fill}" stroke="${n.stroke}" stroke-width="${n.strokeWidth}" opacity="${n.opacity}">${n.containerVisible?shape(n,r):''}${n.iconDataUrl?`<image href="${esc(n.iconDataUrl)}" x="${cx-size/2}" y="${r.y+r.height/2-size/2}" width="${size}" height="${size}" preserveAspectRatio="xMidYMid meet"/>`:''}<text x="${cx}" y="${r.y+r.height+20}" text-anchor="middle" fill="#0f172a" stroke="none" font-family="Inter,Arial" font-weight="700" font-size="15">${esc(n.title)}</text><text x="${cx}" y="${r.y+r.height+38}" text-anchor="middle" fill="#64748b" stroke="none" font-family="Inter,Arial" font-size="12">${esc(n.subtitle)}</text><text x="${cx}" y="${r.y+r.height+54}" text-anchor="middle" fill="#64748b" stroke="none" font-family="Inter,Arial" font-size="11">${esc(n.visibleValue)}</text></g>`}).join('')}
  ${project.texts.map(t=>`<text x="${t.x}" y="${t.y}" text-anchor="${t.align}" fill="${t.color}" font-family="Inter,Arial" font-size="${t.fontSize}" font-weight="${t.fontWeight}">${esc(t.text)}</text>`).join('')}</svg>`;
}
