import type { AtlasProject } from '../model/project';

export function interactiveViewerHtml(project: AtlasProject): string {
  const json = JSON.stringify(project).replaceAll('</script', '<\\/script');
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${project.title}</title><style>
  *{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;font-family:Inter,system-ui;background:#111827;color:#e5e7eb}#stage{width:100%;height:100%;cursor:grab}#stage.drag{cursor:grabbing}.panel{position:fixed;z-index:4;right:16px;top:16px;width:min(340px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;padding:16px;border:1px solid #334155;border-radius:12px;background:#0f172eea;box-shadow:0 20px 60px #0008}.panel:empty{display:none}h1{font-size:18px;margin:0 0 8px}.meta{color:#94a3b8;font-size:12px;line-height:1.5}.close{float:right;background:none;border:0;color:#94a3b8;font-size:20px;cursor:pointer}.node{cursor:pointer}.label{paint-order:stroke;stroke:${project.board.background};stroke-width:5px;stroke-linejoin:round}.help{position:fixed;left:12px;bottom:12px;padding:8px 10px;border-radius:7px;background:#0f172ecc;color:#94a3b8;font-size:11px}
  </style></head><body><svg id="stage"><g id="world"></g></svg><aside id="panel" class="panel"></aside><div class="help">Rueda: zoom · Arrastrar: mover · Clic: abrir ficha</div><script>
  const project=${json},svg=document.querySelector('#stage'),world=document.querySelector('#world'),panel=document.querySelector('#panel');let camera={x:20,y:20,z:.25},drag=null;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const center=n=>({x:n.x+n.width/2,y:n.y+n.height/2}),nodes=new Map(project.nodes.map(n=>[n.id,n]));function path(e){const a=center(nodes.get(e.sourceId)),b=center(nodes.get(e.targetId));if(e.route==='straight')return 'M'+a.x+' '+a.y+'L'+b.x+' '+b.y;if(e.route==='orthogonal'){const x=(a.x+b.x)/2;return 'M'+a.x+' '+a.y+'L'+x+' '+a.y+'L'+x+' '+b.y+'L'+b.x+' '+b.y}const x=(a.x+b.x)/2;return 'M'+a.x+' '+a.y+'C'+x+' '+a.y+','+x+' '+b.y+','+b.x+' '+b.y}
  function render(){world.setAttribute('transform','translate('+camera.x+' '+camera.y+') scale('+camera.z+')');world.innerHTML='<rect width="'+project.board.width+'" height="'+project.board.height+'" fill="'+project.board.background+'"/>'+project.edges.map(e=>nodes.has(e.sourceId)&&nodes.has(e.targetId)?'<path d="'+path(e)+'" fill="none" stroke="'+e.color+'" stroke-width="'+e.width+'" stroke-dasharray="'+e.dash+'"/>':'').join('')+project.events.map(e=>'<g><line x1="'+e.x+'" x2="'+(e.x+e.width)+'" y1="'+e.y+'" y2="'+e.y+'" stroke="'+e.color+'" stroke-width="'+e.lineWidth+'"/><text x="'+e.x+'" y="'+(e.y-10)+'" fill="'+e.color+'">'+esc(e.title)+'</text></g>').join('')+project.nodes.map(n=>'<g class="node" data-id="'+n.id+'"><rect x="'+n.x+'" y="'+n.y+'" width="'+n.width+'" height="'+n.height+'" rx="14" fill="'+n.fill+'" stroke="'+n.stroke+'" stroke-width="'+n.strokeWidth+'"/><text class="label" x="'+(n.x+n.width/2)+'" y="'+(n.y+n.height+20)+'" text-anchor="middle" fill="#e5e7eb" font-weight="700">'+esc(n.title)+'</text><text class="label" x="'+(n.x+n.width/2)+'" y="'+(n.y+n.height+38)+'" text-anchor="middle" fill="#94a3b8" font-size="12">'+esc(n.subtitle)+'</text></g>').join('')}
  svg.addEventListener('wheel',e=>{e.preventDefault();const f=Math.exp(-e.deltaY*.001),r=svg.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top,wx=(px-camera.x)/camera.z,wy=(py-camera.y)/camera.z;camera.z=Math.max(.03,Math.min(6,camera.z*f));camera.x=px-wx*camera.z;camera.y=py-wy*camera.z;render()},{passive:false});svg.addEventListener('pointerdown',e=>{const n=e.target.closest('.node');if(n){const item=nodes.get(n.dataset.id);panel.innerHTML='<button class="close">×</button><h1>'+esc(item.title)+'</h1><div class="meta">'+esc(item.subtitle)+'<br>'+esc(item.visibleValue)+'</div><p>'+esc(item.summary)+'</p>';panel.querySelector('.close').onclick=()=>panel.innerHTML='';return}drag={x:e.clientX,y:e.clientY};svg.classList.add('drag');svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;camera.x+=e.clientX-drag.x;camera.y+=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};render()});svg.addEventListener('pointerup',e=>{drag=null;svg.classList.remove('drag');svg.releasePointerCapture(e.pointerId)});render();
  </script></body></html>`;
}
