import { useEffect, useMemo, useRef, useState } from 'react';
import { areaContentRect, axisBands, axisValuePosition, durationSegment, edgePath, eventSegments, nodeCenter, pointInRect, resolvedNodeRect } from '../lib/geometry';
import { useEditorStore } from '../store/editorStore';
import type { Area, AxisDefinition, Point, Selection } from '../model/project';

type PointerState=
  |{mode:'pan';client:Point}
  |{mode:'move'|'marquee';start:Point;current:Point;additive?:boolean}
  |{mode:'move-waypoint';id:string;index:number;start:Point;current:Point}
  |{mode:'resize-reference'|'resize-area';id:string;handle:string;start:Point;current:Point};
type Tick={label:string;position:number;major:boolean;boundary:boolean};
const keyOf=(item:Selection)=>`${item.type}:${item.id}`;

function densify(items:Tick[],axis:AxisDefinition,zoom:number):Tick[]{
  let last=-Infinity;
  return items.slice().sort((a,b)=>a.position-b.position).map(item=>{const screen=item.position*zoom,major=Boolean(item.label)&&(item.boundary||screen-last>=(axis.minLabelSpacing??44));if(major)last=screen;return{...item,major}});
}

export function axisTicks(axis:AxisDefinition,start:number,length:number,zoom:number):Tick[]{
  if(!axis.visible||axis.mode==='none')return[];
  if(axis.mode==='categories'){
    const total=axis.categories.reduce((sum,item)=>sum+Math.max(.01,item.weight),0);let cursor=0;
    const raw=axis.categories.flatMap((category,index)=>{const before=cursor/Math.max(.01,total);cursor+=Math.max(.01,category.weight);const boundaryPosition=start+(axis.reverse?1-before:before)*length,center=axisValuePosition(axis,category.id,start,length)!;return[...(index?[{label:'',position:boundaryPosition,major:false,boundary:true}]:[]),{label:category.label,position:center,major:true,boundary:false}]});
    return densify(raw,axis,zoom);
  }
  const ranges=axis.segments.length?axis.segments:[{id:'default',from:axis.min,to:axis.max,step:axis.step,weight:1}],result:Tick[]=[];
  for(const [rangeIndex,range] of ranges.entries()){
    const direction=range.to>=range.from?1:-1,span=Math.abs(range.to-range.from),base=Math.max(.000001,Math.abs(range.step));
    const estimated=span/base,skip=Math.max(1,Math.ceil(estimated/450)),step=base*skip*direction;
    for(let value=range.from,count=0;(direction>0?value<=range.to+Math.abs(step)/2:value>=range.to-Math.abs(step)/2)&&result.length<900;value+=step,count+=1){const position=axisValuePosition(axis,value,start,length);if(position!=null)result.push({label:Number(value.toPrecision(10)).toLocaleString('es-ES'),position,major:true,boundary:rangeIndex>0&&count===0})}
  }
  return densify(result,axis,zoom);
}

function areaDepth(area:Area,areas:Area[]):number{let depth=0,current=area,guard=0;while(current.parentAreaId&&guard++<areas.length){const parent=areas.find(item=>item.id===current.parentAreaId);if(!parent)break;depth+=1;current=parent}return depth}
function areaPath(area:Area,areas:Area[]):Area[]{const result=[area];let current=area,guard=0;while(current.parentAreaId&&guard++<areas.length){const parent=areas.find(item=>item.id===current.parentAreaId);if(!parent)break;result.unshift(parent);current=parent}return result}

export function Canvas():React.JSX.Element{
  const svg=useRef<SVGSVGElement>(null),[pointer,setPointer]=useState<PointerState|null>(null),[viewport,setViewport]=useState({width:1200,height:800});
  const project=useEditorStore(s=>s.project),camera=useEditorStore(s=>s.camera),tool=useEditorStore(s=>s.tool),selection=useEditorStore(s=>s.selection),relationSourceId=useEditorStore(s=>s.relationSourceId);
  const setCamera=useEditorStore(s=>s.setCamera),select=useEditorStore(s=>s.select),setSelection=useEditorStore(s=>s.setSelection),clearSelection=useEditorStore(s=>s.clearSelection),addNode=useEditorStore(s=>s.addNode),addEvent=useEditorStore(s=>s.addEvent),addText=useEditorStore(s=>s.addText),relationClick=useEditorStore(s=>s.relationClick),moveSelection=useEditorStore(s=>s.moveSelection),updateProject=useEditorStore(s=>s.updateProject);
  useEffect(()=>{if(!svg.current)return;const observer=new ResizeObserver(entries=>{const rect=entries[0]?.contentRect;if(rect)setViewport({width:rect.width,height:rect.height})});observer.observe(svg.current);return()=>observer.disconnect()},[]);
  const selected=useMemo(()=>new Set(selection.map(keyOf)),[selection]),visibleLayers=useMemo(()=>new Set(project.layers.filter(x=>x.visible).map(x=>x.id)),[project.layers]),nodeMap=useMemo(()=>new Map(project.nodes.map(x=>[x.id,x])),[project.nodes]);
  const worldPoint=(event:{clientX:number;clientY:number}):Point=>{const rect=svg.current!.getBoundingClientRect();return{x:(event.clientX-rect.left-camera.x)/camera.zoom,y:(event.clientY-rect.top-camera.y)/camera.zoom}};

  const beginPointer=(event:React.PointerEvent<SVGSVGElement>)=>{
    if(event.button===1){event.preventDefault();setPointer({mode:'pan',client:{x:event.clientX,y:event.clientY}});event.currentTarget.setPointerCapture(event.pointerId);return}
    if(event.button!==0)return;const target=(event.target as Element).closest<SVGElement>('[data-kind]'),point=worldPoint(event);
    if(tool==='node')return addNode(point);if(tool==='event')return addEvent(point);if(tool==='text')return addText(point);if(tool==='edge'&&target?.dataset.kind==='node')return relationClick(target.dataset.id!);
    if(target&&tool!=='pan'){
      const raw=target.dataset.kind!,id=target.dataset.id!;
      if(raw==='reference-handle'||raw==='area-handle')setPointer({mode:raw==='area-handle'?'resize-area':'resize-reference',id,handle:target.dataset.handle!,start:point,current:point});
      else if(raw==='waypoint')setPointer({mode:'move-waypoint',id,index:Number(target.dataset.index),start:point,current:point});
      else{select({type:raw as Selection['type'],id} as Selection,event.shiftKey);setPointer({mode:'move',start:point,current:point})}
      event.currentTarget.setPointerCapture(event.pointerId);return;
    }
    if(tool==='pan')setPointer({mode:'pan',client:{x:event.clientX,y:event.clientY}});else{if(!event.shiftKey)clearSelection();setPointer({mode:'marquee',start:point,current:point,additive:event.shiftKey})}event.currentTarget.setPointerCapture(event.pointerId);
  };
  const movePointer=(event:React.PointerEvent<SVGSVGElement>)=>{if(!pointer)return;if(pointer.mode==='pan'){setCamera({...camera,x:camera.x+event.clientX-pointer.client.x,y:camera.y+event.clientY-pointer.client.y});setPointer({mode:'pan',client:{x:event.clientX,y:event.clientY}})}else setPointer({...pointer,current:worldPoint(event)} as PointerState)};
  const endPointer=(event:React.PointerEvent<SVGSVGElement>)=>{
    if(!pointer)return;
    if(pointer.mode==='move'){const dx=pointer.current.x-pointer.start.x,dy=pointer.current.y-pointer.start.y;if(Math.abs(dx)+Math.abs(dy)>.5)moveSelection(dx,dy)}
    else if(pointer.mode==='marquee'){const found:Selection[]=[];for(const node of project.nodes)if(pointInRect(nodeCenter(node,project),pointer.start,pointer.current))found.push({type:'node',id:node.id});for(const item of project.events)if(pointInRect({x:item.x+item.width/2,y:item.y},pointer.start,pointer.current))found.push({type:'event',id:item.id});for(const item of project.texts)if(pointInRect({x:item.x,y:item.y},pointer.start,pointer.current))found.push({type:'text',id:item.id});for(const item of project.references)if(pointInRect({x:item.x+item.width/2,y:item.y+item.height/2},pointer.start,pointer.current))found.push({type:'reference',id:item.id});for(const item of project.areas)if(pointInRect({x:item.x+item.width/2,y:item.y+item.height/2},pointer.start,pointer.current))found.push({type:'area',id:item.id});setSelection(pointer.additive?[...selection,...found.filter(x=>!selected.has(keyOf(x)))]:found)}
    else if(pointer.mode==='move-waypoint'){const dx=pointer.current.x-pointer.start.x,dy=pointer.current.y-pointer.start.y;updateProject('Mover punto de paso',draft=>{const point=draft.edges.find(edge=>edge.id===pointer.id)?.waypoints[pointer.index];if(point){point.x+=dx;point.y+=dy}})}
    else if(pointer.mode==='resize-reference'){const original=project.references.find(x=>x.id===pointer.id);if(original){const dx=pointer.current.x-pointer.start.x,dy=pointer.current.y-pointer.start.y;updateProject('Redimensionar referencia',draft=>{const item=draft.references.find(x=>x.id===pointer.id)!,west=pointer.handle.includes('w'),north=pointer.handle.includes('n');let width=Math.max(20,original.width+(west?-dx:dx)),height=Math.max(20,original.height+(north?-dy:dy));if(original.lockAspect||event.shiftKey){const ratio=original.width/original.height;if(Math.abs(dx)>=Math.abs(dy))height=width/ratio;else width=height*ratio}if(west)item.x=original.x+original.width-width;if(north)item.y=original.y+original.height-height;item.width=width;item.height=height})}}
    else if(pointer.mode==='resize-area'){const original=project.areas.find(x=>x.id===pointer.id);if(original){const dx=pointer.current.x-pointer.start.x,dy=pointer.current.y-pointer.start.y;updateProject('Redimensionar área',draft=>{const item=draft.areas.find(x=>x.id===pointer.id)!,w=pointer.handle.includes('w'),e=pointer.handle.includes('e'),n=pointer.handle.includes('n'),s=pointer.handle.includes('s');if(w){item.x=Math.min(original.x+original.width-80,original.x+dx);item.width=original.width+original.x-item.x}if(e)item.width=Math.max(80,original.width+dx);if(n){item.y=Math.min(original.y+original.height-80,original.y+dy);item.height=original.height+original.y-item.y}if(s)item.height=Math.max(80,original.height+dy)})}}
    if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);setPointer(null);
  };
  const wheel=(event:React.WheelEvent<SVGSVGElement>)=>{event.preventDefault();const rect=svg.current!.getBoundingClientRect(),px=event.clientX-rect.left,py=event.clientY-rect.top,wx=(px-camera.x)/camera.zoom,wy=(py-camera.y)/camera.zoom,zoom=Math.max(.03,Math.min(8,camera.zoom*Math.exp(-event.deltaY*.0012)));setCamera({zoom,x:px-wx*zoom,y:py-wy*zoom})};

  const axisTickMap=useMemo(()=>({x:axisTicks(project.board.axes.x,60,project.board.width-120,camera.zoom),y:axisTicks(project.board.axes.y,60,project.board.height-120,camera.zoom)}),[project.board,camera.zoom]);
  const generalBands=useMemo(()=>({x:axisBands(project.board.axes.x,60,project.board.width-120),y:axisBands(project.board.axes.y,60,project.board.height-120)}),[project.board.axes,project.board.width,project.board.height]);
  const localAxisTicks=useMemo(()=>project.areas.flatMap(area=>{const rect=areaContentRect(area,project);return(['x','y'] as const).flatMap(orientation=>{const binding=area.axisBindings[orientation];if(!binding.visible||!['local-project','local-custom'].includes(binding.mode))return[];const axis={...(binding.mode==='local-custom'?binding.axis:project.board.axes[orientation]),visible:true};return axisTicks(axis,orientation==='x'?rect.x:rect.y,orientation==='x'?rect.width:rect.height,camera.zoom).map(tick=>({area,orientation,tick,axis}))})}),[project,camera.zoom]);
  const viewCenter={x:(viewport.width/2-camera.x)/camera.zoom,y:(viewport.height/2-camera.y)/camera.zoom};
  const containing=project.areas.filter(area=>viewCenter.x>=area.x&&viewCenter.x<=area.x+area.width&&viewCenter.y>=area.y&&viewCenter.y<=area.y+area.height).sort((a,b)=>areaDepth(b,project.areas)-areaDepth(a,project.areas)||(a.width*a.height-b.width*b.height));
  const activeArea=containing[0],breadcrumbs=activeArea?areaPath(activeArea,project.areas):[];
  const stickyFor=(orientation:'x'|'y')=>{
    const local=containing.find(area=>{const binding=area.axisBindings[orientation];if(!binding.visible||!['local-project','local-custom'].includes(binding.mode))return false;const axis=binding.mode==='local-custom'?binding.axis:project.board.axes[orientation];return axis.mode!=='none'});
    if(local){const binding=local.axisBindings[orientation],axis=binding.mode==='local-custom'?binding.axis:project.board.axes[orientation],rect=areaContentRect(local,project);return axis.sticky!==false?{axis,area:local,ticks:axisTicks({...axis,visible:true},orientation==='x'?rect.x:rect.y,orientation==='x'?rect.width:rect.height,camera.zoom)}:null}
    const axis=project.board.axes[orientation];return axis.visible&&axis.mode!=='none'&&axis.sticky!==false?{axis,area:null,ticks:axisTickMap[orientation]}:null;
  };
  const stickyX=stickyFor('x'),stickyY=stickyFor('y');
  const preview=pointer?.mode==='move'?{x:pointer.current.x-pointer.start.x,y:pointer.current.y-pointer.start.y}:{x:0,y:0},offset=(type:Selection['type'],id:string)=>selected.has(`${type}:${id}`)?preview:{x:0,y:0};
  const handles=(item:{x:number;y:number;width:number;height:number})=>[['nw',item.x,item.y],['n',item.x+item.width/2,item.y],['ne',item.x+item.width,item.y],['e',item.x+item.width,item.y+item.height/2],['se',item.x+item.width,item.y+item.height],['s',item.x+item.width/2,item.y+item.height],['sw',item.x,item.y+item.height],['w',item.x,item.y+item.height/2]] as Array<[string,number,number]>;
  const areasByDepth=project.areas.filter(x=>visibleLayers.has(x.layerId)).slice().sort((a,b)=>areaDepth(a,project.areas)-areaDepth(b,project.areas));

  return <main className="canvas-shell" data-tool={tool}><svg ref={svg} className="canvas" onPointerDown={beginPointer} onPointerMove={movePointer} onPointerUp={endPointer} onPointerCancel={endPointer} onWheel={wheel} onContextMenu={event=>event.preventDefault()}>
    <defs><pattern id="grid" width={project.board.gridSize} height={project.board.gridSize} patternUnits="userSpaceOnUse"><path d={`M ${project.board.gridSize} 0 L 0 0 0 ${project.board.gridSize}`} fill="none" stroke={project.board.gridColor} strokeOpacity={project.board.gridOpacity} strokeWidth="1" vectorEffect="non-scaling-stroke"/></pattern><marker id="marker-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/></marker><marker id="marker-circle" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><circle cx="5" cy="5" r="4" fill="context-stroke"/></marker><marker id="marker-diamond" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M 5 0 L 10 5 L 5 10 L 0 5 Z" fill="context-stroke"/></marker><marker id="marker-bar" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 5 0 L 5 10" stroke="context-stroke" strokeWidth="2"/></marker>{project.edges.filter(e=>e.colors.length>1).map(e=>{const source=nodeMap.get(e.sourceId),target=nodeMap.get(e.targetId),a=source?nodeCenter(source,project):{x:0,y:0},b=target?nodeCenter(target,project):{x:1,y:0};return <linearGradient key={e.id} id={`gradient-${e.id}`} gradientUnits="userSpaceOnUse" x1={a.x} y1={a.y} x2={b.x} y2={b.y}>{e.colors.map((color,index)=><stop key={index} offset={`${index/Math.max(1,e.colors.length-1)*100}%`} stopColor={color}/>)}</linearGradient>})}</defs>
    <g transform={`translate(${camera.x} ${camera.y}) scale(${camera.zoom})`}>
      <rect width={project.board.width} height={project.board.height} fill={project.board.background} fillOpacity={project.board.backgroundOpacity}/>{generalBands.x.filter(b=>b.color!=='transparent'&&b.opacity>0).map(b=><rect key={`band-x-${b.id}`} x={b.start} y="0" width={b.length} height={project.board.height} fill={b.color} fillOpacity={b.opacity} pointerEvents="none"/>)}{generalBands.y.filter(b=>b.color!=='transparent'&&b.opacity>0).map(b=><rect key={`band-y-${b.id}`} x="0" y={b.start} width={project.board.width} height={b.length} fill={b.color} fillOpacity={b.opacity} pointerEvents="none"/>)}{project.board.gridVisible&&<rect width={project.board.width} height={project.board.height} fill="url(#grid)"/>}
      {project.references.filter(x=>x.visible&&visibleLayers.has(x.layerId)).map(item=>{const d=offset('reference',item.id);return <g key={item.id} data-kind="reference" data-id={item.id} transform={`translate(${d.x} ${d.y}) rotate(${item.rotation} ${item.x+item.width/2} ${item.y+item.height/2})`}><image href={item.dataUrl} x={item.x} y={item.y} width={item.width} height={item.height} opacity={item.opacity} preserveAspectRatio="none"/>{selected.has(`reference:${item.id}`)&&<><rect className="selection-box" x={item.x} y={item.y} width={item.width} height={item.height}/>{handles(item).filter(([h])=>h.length===2).map(([h,x,y])=><circle key={h} data-kind="reference-handle" data-id={item.id} data-handle={h} className="resize-handle" cx={x} cy={y} r={8/camera.zoom}/>)}</>}</g>})}
      {areasByDepth.map(item=><g key={item.id} data-kind="area" data-id={item.id}><rect x={item.x} y={item.y} width={item.width} height={item.height} rx={item.radius} fill={item.fill} fillOpacity={item.fillOpacity} stroke={item.stroke} strokeWidth={item.strokeWidth}/>{item.showTitle!==false&&<text x={item.x+12/camera.zoom} y={item.y+(item.titleSize??16)+8/camera.zoom} fill={item.titleColor??item.stroke} fontSize={(item.titleSize??16)/camera.zoom} fontWeight="750" className="area-title">{item.name}</text>}{selected.has(`area:${item.id}`)&&<><rect className="selection-box" x={item.x} y={item.y} width={item.width} height={item.height}/>{handles(item).map(([h,x,y])=><circle key={h} data-kind="area-handle" data-id={item.id} data-handle={h} className={`resize-handle handle-${h}`} cx={x} cy={y} r={8/camera.zoom}/>)}</>}</g>)}
      {axisTickMap.y.map(t=><g key={`general-y-${t.label}-${t.position}`}><line x1="0" x2={project.board.width} y1={t.position} y2={t.position} className={`axis-line ${t.major?'major':''} ${t.boundary?'axis-break':''}`}/>{project.board.axes.y.sticky===false&&t.major&&<text x={14/camera.zoom} y={t.position-6/camera.zoom} className="axis-label" fontSize={(project.board.axes.y.labelSize??10)/camera.zoom}>{t.label}</text>}</g>)}
      {axisTickMap.x.map(t=><g key={`general-x-${t.label}-${t.position}`}><line x1={t.position} x2={t.position} y1="0" y2={project.board.height} className={`axis-line ${t.major?'major':''} ${t.boundary?'axis-break':''}`}/>{project.board.axes.x.sticky===false&&t.major&&<text x={t.position+6/camera.zoom} y={16/camera.zoom} className="axis-label" fontSize={(project.board.axes.x.labelSize??10)/camera.zoom}>{t.label}</text>}</g>)}
      {localAxisTicks.map(({area,orientation,tick,axis})=>orientation==='y'?<g key={`local-y-${area.id}-${tick.label}-${tick.position}`}><line x1={area.x+area.padding.left} x2={area.x+area.width-area.padding.right} y1={tick.position} y2={tick.position} className={`axis-line local ${tick.major?'major':''} ${tick.boundary?'axis-break':''}`}/>{axis.sticky===false&&tick.major&&<text x={area.x+6/camera.zoom} y={tick.position-5/camera.zoom} className="axis-label" fontSize={(axis.labelSize??10)/camera.zoom}>{tick.label}</text>}</g>:<g key={`local-x-${area.id}-${tick.label}-${tick.position}`}><line x1={tick.position} x2={tick.position} y1={area.y+area.padding.top} y2={area.y+area.height-area.padding.bottom} className={`axis-line local ${tick.major?'major':''} ${tick.boundary?'axis-break':''}`}/>{axis.sticky===false&&tick.major&&<text x={tick.position+5/camera.zoom} y={area.y+14/camera.zoom} className="axis-label" fontSize={(axis.labelSize??10)/camera.zoom}>{tick.label}</text>}</g>)}
      {project.nodes.filter(x=>visibleLayers.has(x.layerId)).map(node=>{const segment=durationSegment(node,project);return segment?<line key={`duration-${node.id}`} x1={segment.x} x2={segment.x} y1={segment.y1} y2={segment.y2} stroke={node.fill} strokeWidth={segment.width} opacity={node.opacity*.75} strokeLinecap="round"/>:null})}
      {project.edges.filter(x=>visibleLayers.has(x.layerId)).map(edge=>{const source=nodeMap.get(edge.sourceId),target=nodeMap.get(edge.targetId);if(!source||!target)return null;const path=edgePath(edge,source,target,project);return <g key={edge.id} data-kind="edge" data-id={edge.id} className={selected.has(`edge:${edge.id}`)?'selected-object':''}><path d={path} fill="none" stroke={edge.colors.length>1?`url(#gradient-${edge.id})`:edge.color} strokeWidth={edge.width} strokeDasharray={edge.dash} strokeLinecap={edge.lineCap} opacity={edge.opacity} markerStart={edge.startMarker!=='none'?`url(#marker-${edge.startMarker})`:undefined} markerEnd={edge.endMarker!=='none'?`url(#marker-${edge.endMarker})`:undefined} className="edge-path"/><path d={path} fill="none" stroke="transparent" strokeWidth={Math.max(16,edge.width+10)} className="edge-hit"/>{selected.has(`edge:${edge.id}`)&&edge.waypoints.map((p,i)=><circle key={i} data-kind="waypoint" data-id={edge.id} data-index={i} cx={p.x} cy={p.y} r={7/camera.zoom} className="waypoint-handle"/>)}</g>})}
      {project.events.filter(x=>visibleLayers.has(x.layerId)).map(item=>{const d=offset('event',item.id),segments=eventSegments(item,project),first=segments[0];return <g key={item.id} data-kind="event" data-id={item.id} transform={`translate(${d.x} ${d.y})`} className={selected.has(`event:${item.id}`)?'selected-object':''}>{segments.map((segment,index)=><g key={index}><line x1={segment.x1} x2={segment.x2} y1={segment.y} y2={segment.y} stroke={item.color} strokeWidth={item.lineWidth} strokeDasharray={item.dash}/><path d={`M ${segment.x1} ${segment.y} L ${segment.x2} ${segment.y}`} stroke="transparent" strokeWidth="20"/></g>)}<text x={first.x1} y={first.y-11} fill={item.color} className="event-title">{item.title}</text></g>})}
      {project.nodes.filter(x=>visibleLayers.has(x.layerId)).map(node=>{const d=offset('node',node.id),rect=resolvedNodeRect(node,project),x=rect.x+d.x,y=rect.y+d.y,cx=x+node.width/2,cy=y+node.height/2,r=Math.min(node.width,node.height)/2,iconSize=Math.min(node.width,node.height)*(node.containerVisible?.58:.9)*node.iconScale;return <g key={node.id} data-kind="node" data-id={node.id} className={`node-object ${selected.has(`node:${node.id}`)?'selected-object':''}`} opacity={node.opacity} transform={`rotate(${node.rotation} ${cx} ${cy})`}>{node.containerVisible&&(node.shape==='sphere'?<><circle cx={cx} cy={cy} r={r} fill={node.fill} stroke={node.stroke} strokeWidth={node.strokeWidth}/><circle cx={cx-r*.28} cy={cy-r*.28} r={r*.28} fill="#fff" opacity=".22" pointerEvents="none"/></>:node.shape==='circle'?<circle cx={cx} cy={cy} r={r} fill={node.fill} stroke={node.stroke} strokeWidth={node.strokeWidth}/>:node.shape==='diamond'?<path d={`M ${cx} ${y} L ${x+node.width} ${cy} L ${cx} ${y+node.height} L ${x} ${cy} Z`} fill={node.fill} stroke={node.stroke} strokeWidth={node.strokeWidth}/>:<rect x={x} y={y} width={node.width} height={node.height} rx={node.shape==='pill'?node.height/2:node.shape==='rounded'?14:0} fill={node.fill} stroke={node.stroke} strokeWidth={node.strokeWidth}/>)}{node.iconDataUrl&&<><rect x={cx-iconSize/2-3} y={cy-iconSize/2-3} width={iconSize+6} height={iconSize+6} rx={node.containerVisible?Math.min(20,iconSize/2):0} fill={node.iconBackground||'transparent'}/><image href={node.iconDataUrl} x={cx-iconSize/2} y={cy-iconSize/2} width={iconSize} height={iconSize} preserveAspectRatio="xMidYMid meet" style={{filter:node.iconInvert?'invert(1)':undefined}}/></>}<text x={cx} y={y+node.height+21} textAnchor="middle" className="node-title">{node.title}</text>{node.subtitle&&<text x={cx} y={y+node.height+39} textAnchor="middle" className="node-subtitle">{node.subtitle}</text>}{node.visibleValue&&<text x={cx} y={y+node.height+55} textAnchor="middle" className="node-value">{node.visibleValue}</text>}{relationSourceId===node.id&&<circle cx={cx} cy={cy} r={r+12} className="relation-source"/>}</g>})}
      {project.texts.filter(x=>visibleLayers.has(x.layerId)).map(item=>{const d=offset('text',item.id);return <text key={item.id} data-kind="text" data-id={item.id} x={item.x+d.x} y={item.y+d.y} textAnchor={item.align} fill={item.color} fontSize={item.fontSize} fontWeight={item.fontWeight} className={selected.has(`text:${item.id}`)?'selected-text':''}>{item.text}</text>})}
      {pointer?.mode==='marquee'&&<rect className="marquee" x={Math.min(pointer.start.x,pointer.current.x)} y={Math.min(pointer.start.y,pointer.current.y)} width={Math.abs(pointer.current.x-pointer.start.x)} height={Math.abs(pointer.current.y-pointer.start.y)}/>} 
    </g>
    {(stickyX||stickyY)&&<g className="sticky-rulers" pointerEvents="none">{stickyY&&<><rect x="0" y="0" width="76" height={viewport.height} className="sticky-ruler-bg"/><line x1="75" x2="75" y1="0" y2={viewport.height} className="sticky-ruler-edge"/>{stickyY.ticks.filter(t=>t.major).map(t=>{const y=camera.y+t.position*camera.zoom;if(y<24||y>viewport.height-4)return null;return <g key={`sticky-y-${t.position}`}><line x1="65" x2="75" y1={y} y2={y} className="sticky-ruler-tick"/><text x="61" y={y+stickyY.axis.labelSize*.34} textAnchor="end" fontSize={stickyY.axis.labelSize} className="sticky-ruler-label">{t.label}</text></g>})}<text x="7" y={viewport.height-10} className="sticky-ruler-name">{stickyY.area?.name??stickyY.axis.label}</text></>}{stickyX&&<><rect x="0" y="0" width={viewport.width} height="32" className="sticky-ruler-bg"/><line x1="0" x2={viewport.width} y1="31" y2="31" className="sticky-ruler-edge"/>{stickyX.ticks.filter(t=>t.major).map(t=>{const x=camera.x+t.position*camera.zoom;if(x<80||x>viewport.width-4)return null;return <g key={`sticky-x-${t.position}`}><line x1={x} x2={x} y1="22" y2="31" className="sticky-ruler-tick"/><text x={x} y="16" textAnchor="middle" fontSize={stickyX.axis.labelSize} className="sticky-ruler-label">{t.label}</text></g>})}<text x={stickyY?82:8} y="22" className="sticky-ruler-name">{stickyX.area?.name??stickyX.axis.label}</text></>}{stickyX&&stickyY&&<rect x="0" y="0" width="76" height="32" className="sticky-ruler-corner"/>}{breadcrumbs.length>0&&<g><rect x={stickyY?82:8} y={stickyX?38:8} width={Math.min(viewport.width-100,Math.max(120,breadcrumbs.map(a=>a.name).join(' › ').length*7+20))} height="24" rx="6" className="area-breadcrumb-bg"/><text x={stickyY?92:18} y={stickyX?54:24} className="area-breadcrumb">{breadcrumbs.map(a=>a.name).join(' › ')}</text></g>}</g>}
  </svg><div className="canvas-status"><span>{Math.round(camera.zoom*100)}%</span><span>{project.nodes.length} entidades · {project.edges.length} conexiones · {project.events.length} acontecimientos</span></div></main>;
}
