import { useEffect, useMemo, useState } from 'react';
import { Database, Download, Play, RefreshCw, Table2, TerminalSquare, Trash2, X } from 'lucide-react';
import { useEditorStore } from '../store/editorStore';
import { downloadBlob, downloadText, safeFileName } from '../lib/download';
import { openProjectDatabase, projectToDatabase } from '../lib/sqlite';

type View='browser'|'console'|'history';
interface ResultSet { columns:string[]; values:unknown[][] }
interface DbObject { name:string; type:string; sql:string }
const display=(value:unknown)=>value instanceof Uint8Array?`[BLOB ${value.byteLength} bytes]`:value==null?'NULL':String(value);
const ident=(value:string)=>`"${value.replaceAll('"','""')}"`;

export function DatabaseDialog({onClose}:{onClose:()=>void}):React.JSX.Element{
  const project=useEditorStore(s=>s.project),update=useEditorStore(s=>s.updateProject);
  const [view,setView]=useState<View>('browser'),[objects,setObjects]=useState<DbObject[]>([]),[selected,setSelected]=useState('project'),[schema,setSchema]=useState<ResultSet|null>(null),[rows,setRows]=useState<ResultSet|null>(null),[query,setQuery]=useState('SELECT name, type, sql\nFROM sqlite_master\nWHERE name NOT LIKE \'sqlite_%\'\nORDER BY type, name;'),[result,setResult]=useState<ResultSet|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const name=safeFileName(project.title);
  const refresh=async()=>{setBusy(true);setMessage('');try{const db=await openProjectDatabase(project);const list=db.exec("SELECT name, type, COALESCE(sql, '') FROM sqlite_master WHERE type IN ('table','view') AND name NOT LIKE 'sqlite_%' ORDER BY type, name")[0];setObjects((list?.values??[]).map(value=>({name:String(value[0]),type:String(value[1]),sql:String(value[2])})));if(selected){const info=db.exec(`PRAGMA table_info(${ident(selected)})`)[0],data=db.exec(`SELECT * FROM ${ident(selected)} LIMIT 200`)[0];setSchema(info?{columns:info.columns,values:info.values}:null);setRows(data?{columns:data.columns,values:data.values}:null)}db.close()}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  useEffect(()=>{void refresh()},[project,selected]);
  const execute=async()=>{if(!query.trim())return;const mutation=!/^\s*(SELECT|PRAGMA|EXPLAIN|WITH)\b/i.test(query);if(mutation&&/\b(DROP|DELETE|TRUNCATE)\b/i.test(query)&&!confirm('Esta consulta contiene una eliminación. ¿Ejecutarla y guardarla en el historial del proyecto?'))return;setBusy(true);setMessage('');try{const db=await openProjectDatabase(project);const output=db.exec(query);db.close();setResult(output[0]?{columns:output[0].columns,values:output[0].values}:null);if(mutation){update('Ejecutar SQL personalizado',draft=>{draft.database.customSql.push(query.trim())});setMessage('Sentencia validada y guardada. Se reproducirá al generar el SQLite.')}else setMessage(`${output[0]?.values.length??0} fila(s) devuelta(s).`)}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
  const exportDb=async()=>downloadBlob(new Blob([new Uint8Array(await projectToDatabase(project))],{type:'application/vnd.sqlite3'}),`${name}.sqlite`);
  const object=objects.find(item=>item.name===selected);
  const table=(data:ResultSet|null)=><div className="db-table-wrap">{data?<table className="db-table"><thead><tr>{data.columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{data.values.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column} title={display(value)}>{display(value)}</td>)}</tr>)}</tbody></table>:<div className="empty-state">La consulta no devolvió una tabla.</div>}</div>;
  const stats=useMemo(()=>`${objects.filter(x=>x.type==='table').length} tablas · ${objects.filter(x=>x.type==='view').length} vistas · ${project.database.customSql.length} sentencias persistentes`,[objects,project.database.customSql.length]);
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="database-dialog"><header><div><small>SQLITE STUDIO</small><h2>{project.title}</h2><span>{stats}</span></div><div className="db-actions"><button className="small" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={14}/> Actualizar</button><button className="small" onClick={()=>void exportDb()}><Download size={14}/> SQLite</button><button className="icon" onClick={onClose}><X size={19}/></button></div></header><nav className="project-tabs db-tabs"><button className={view==='browser'?'active':''} onClick={()=>setView('browser')}><Table2 size={16}/><strong>Explorador</strong><small>Tablas, esquema y datos</small></button><button className={view==='console'?'active':''} onClick={()=>setView('console')}><TerminalSquare size={16}/><strong>Consola SQL</strong><small>Consultas y cambios</small></button><button className={view==='history'?'active':''} onClick={()=>setView('history')}><Database size={16}/><strong>SQL persistente</strong><small>Tablas y datos propios</small></button></nav>{message&&<div className={`db-message ${/error|no se puede|near /i.test(message)?'error':''}`}>{message}</div>}
    {view==='browser'&&<div className="db-browser"><aside>{objects.map(item=><button key={item.name} className={selected===item.name?'active':''} onClick={()=>setSelected(item.name)}><Table2 size={14}/><span>{item.name}</span><small>{item.type}</small></button>)}</aside><main><section><h3>{selected}</h3><pre className="db-schema-sql">{object?.sql||'Vista o tabla sin SQL de creación disponible.'}</pre></section><section><h3>Columnas</h3>{table(schema)}</section><section><h3>Primeras 200 filas</h3>{table(rows)}</section></main></div>}
    {view==='console'&&<div className="db-console"><div className="console-editor"><div className="section-heading"><h3>SQL</h3><div><button className="small" onClick={()=>setQuery('SELECT * FROM project LIMIT 20;')}>Ejemplo</button><button className="small primary" disabled={busy||!query.trim()} onClick={()=>void execute()}><Play size={14}/> Ejecutar</button></div></div><textarea value={query} spellCheck={false} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void execute()}}}/><p className="muted">Ctrl+Enter ejecuta. SELECT y PRAGMA sólo consultan. CREATE, INSERT, UPDATE, ALTER y demás modificaciones se guardan en el proyecto y se reaplican al exportar.</p></div><section><h3>Resultado</h3>{table(result)}</section></div>}
    {view==='history'&&<div className="db-history"><div className="section-heading"><div><h3>Historial SQL reproducible</h3><p className="muted">Aquí viven tus tablas ocultas, vistas, índices y datos manuales. El orden importa.</p></div><button className="small" disabled={!project.database.customSql.length} onClick={()=>downloadText(project.database.customSql.join('\n\n-- ────────────────────\n\n'),`${name}-custom.sql`,'text/sql')}><Download size={14}/> Script</button></div>{project.database.customSql.map((sql,index)=><article key={`${index}-${sql.slice(0,20)}`}><header><strong>#{index+1}</strong><button className="icon danger" onClick={()=>confirm(`¿Eliminar la sentencia SQL #${index+1}? Las sentencias posteriores podrían depender de ella.`)&&update('Eliminar SQL personalizado',draft=>{draft.database.customSql.splice(index,1)})}><Trash2 size={14}/></button></header><pre>{sql}</pre></article>)}{!project.database.customSql.length&&<div className="empty-state">Aún no hay cambios manuales. Usa la consola para crear tablas, vistas, columnas auxiliares o datos propios.</div>}</div>}
  </div></div>;
}
