import { useRef } from 'react';
import { ImagePlus, Trash2 } from 'lucide-react';
import { useEditorStore } from '../store/editorStore';
import type { AtlasProject, Selection } from '../model/project';

function Field({ label, value, type = 'text', onCommit, min, max, step }: { label: string; value: string | number; type?: string; onCommit: (value: string) => void; min?: number; max?: number; step?: number }): React.JSX.Element {
  return <label className="field"><span>{label}</span><input key={`${label}-${value}`} type={type} defaultValue={value} min={min} max={max} step={step} onBlur={event => onCommit(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); }}/></label>;
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: Array<[string,string]>; onChange: (value: string) => void }): React.JSX.Element {
  return <label className="field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)}>{options.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select></label>;
}
const number = (value: string, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;

export function Inspector(): React.JSX.Element {
  const project = useEditorStore(state => state.project);
  const selection = useEditorStore(state => state.selection);
  const update = useEditorStore(state => state.updateProject);
  const deleteSelection = useEditorStore(state => state.deleteSelection);
  const iconInput = useRef<HTMLInputElement>(null);
  if (selection.length > 1) return <aside className="inspector"><header><small>SELECCIÓN MÚLTIPLE</small><h2>{selection.length} objetos</h2></header><section><p className="muted">Muévelos juntos sobre el lienzo o elimínalos como grupo. Los estilos colectivos se incorporarán sobre esta misma base.</p><button className="danger wide" onClick={() => confirm(`¿Eliminar ${selection.length} objetos?`) && deleteSelection()}><Trash2 size={15}/> Eliminar selección</button></section></aside>;
  if (!selection.length) return <aside className="inspector"><header><small>INSPECTOR</small><h2>Proyecto vacío</h2></header><section><p className="muted">Crea entidades, conexiones, acontecimientos o textos desde la barra izquierda. El lienzo no exige columnas, áreas ni fechas.</p><dl className="stats"><div><dt>Entidades</dt><dd>{project.nodes.length}</dd></div><div><dt>Conexiones</dt><dd>{project.edges.length}</dd></div><div><dt>Capas</dt><dd>{project.layers.length}</dd></div><div><dt>Referencias</dt><dd>{project.references.length}</dd></div></dl></section></aside>;
  const selected = selection[0];
  const commit = (label: string, recipe: (draft: AtlasProject) => void) => update(label, recipe);
  const remove = (name: string) => { if (confirm(`¿Eliminar «${name}»? La operación podrá deshacerse.`)) deleteSelection(); };

  if (selected.type === 'node') {
    const node = project.nodes.find(item => item.id === selected.id)!;
    const edit = <K extends keyof typeof node>(key: K, value: typeof node[K]) => commit('Editar entidad', draft => { const item = draft.nodes.find(current => current.id === node.id)!; item[key] = value; });
    const loadIcon = (file: File) => { const reader = new FileReader(); reader.onload = () => edit('iconDataUrl', String(reader.result)); reader.readAsDataURL(file); };
    return <aside className="inspector"><header><small>ENTIDAD</small><h2>{node.title}</h2></header>
      <section><h3>Visible en el mapa</h3><Field label="Título" value={node.title} onCommit={value => edit('title', value)}/><Field label="Subtítulo" value={node.subtitle} onCommit={value => edit('subtitle', value)}/><Field label="Valor visible" value={node.visibleValue} onCommit={value => edit('visibleValue', value)}/></section>
      <section><h3>Posición y geometría</h3><div className="two"><Field label="X" type="number" value={node.x} onCommit={value => edit('x', number(value,node.x))}/><Field label="Y" type="number" value={node.y} onCommit={value => edit('y', number(value,node.y))}/><Field label="Anchura" type="number" value={node.width} min={20} onCommit={value => edit('width', Math.max(20,number(value,node.width)))}/><Field label="Altura" type="number" value={node.height} min={20} onCommit={value => edit('height', Math.max(20,number(value,node.height)))}/></div><Select label="Forma" value={node.shape} options={[['rounded','Redondeada'],['rectangle','Rectángulo'],['circle','Elipse'],['diamond','Rombo'],['pill','Cápsula']]} onChange={value => edit('shape', value as typeof node.shape)}/></section>
      <section><h3>Estilo</h3><div className="two"><Field label="Relleno" type="color" value={node.fill} onCommit={value => edit('fill',value)}/><Field label="Borde" type="color" value={node.stroke} onCommit={value => edit('stroke',value)}/><Field label="Grosor" type="number" value={node.strokeWidth} min={0} step={.5} onCommit={value => edit('strokeWidth',number(value,node.strokeWidth))}/><Field label="Opacidad" type="number" value={node.opacity} min={0} max={1} step={.05} onCommit={value => edit('opacity',number(value,node.opacity))}/></div></section>
      <section><h3>Icono vectorial</h3><button className="wide" onClick={() => iconInput.current?.click()}><ImagePlus size={15}/> Cargar SVG o imagen</button><input ref={iconInput} hidden type="file" accept="image/*,.svg" onChange={event => { const file=event.target.files?.[0];if(file)loadIcon(file);event.target.value=''; }}/><div className="two"><Field label="Fondo" type="color" value={node.iconBackground || '#ffffff'} onCommit={value => edit('iconBackground',value)}/><label className="check"><input type="checkbox" checked={node.iconInvert ?? false} onChange={event => edit('iconInvert',event.target.checked)}/> Invertir color</label></div>{node.iconDataUrl&&<button className="danger wide" onClick={() => confirm('¿Quitar el icono?')&&edit('iconDataUrl',undefined)}>Quitar icono</button>}</section>
      <section><h3>Ficha interactiva</h3><Select label="Tipo" value={node.type} options={project.catalogs.nodeTypes.map(item=>[item.id,item.label])} onChange={value=>edit('type',value)}/><Select label="Estado" value={node.status} options={project.catalogs.statuses.map(item=>[item.id,item.label])} onChange={value=>edit('status',value)}/><label className="field"><span>Resumen</span><textarea key={node.summary} defaultValue={node.summary} onBlur={event=>edit('summary',event.target.value)}/></label></section>
      <section><button className="danger wide" onClick={()=>remove(node.title)}><Trash2 size={15}/> Eliminar entidad</button></section></aside>;
  }
  if (selected.type === 'edge') {
    const edge=project.edges.find(item=>item.id===selected.id)!;const edit=<K extends keyof typeof edge>(key:K,value:typeof edge[K])=>commit('Editar conexión',draft=>{draft.edges.find(item=>item.id===edge.id)![key]=value});
    return <aside className="inspector"><header><small>CONEXIÓN</small><h2>{edge.label||'Sin etiqueta'}</h2></header><section><Field label="Etiqueta" value={edge.label} onCommit={value=>edit('label',value)}/><Select label="Tipo" value={edge.kind} options={project.catalogs.edgeKinds.map(item=>[item.id,item.label])} onChange={value=>edit('kind',value)}/><Select label="Recorrido" value={edge.route} options={[['curve','Curva'],['orthogonal','Ortogonal'],['straight','Recta']]} onChange={value=>edit('route',value as typeof edge.route)}/><label className="check"><input type="checkbox" checked={edge.directed} onChange={event=>edit('directed',event.target.checked)}/> Relación dirigida</label></section><section><h3>Trazo</h3><div className="two"><Field label="Color" type="color" value={edge.color} onCommit={value=>edit('color',value)}/><Field label="Grosor" type="number" value={edge.width} min={.2} step={.2} onCommit={value=>edit('width',number(value,edge.width))}/></div><Field label="Patrón SVG" value={edge.dash} onCommit={value=>edit('dash',value)}/><Field label="Gradiente (colores separados por coma)" value={edge.colors.join(', ')} onCommit={value=>edit('colors',value.split(',').map(x=>x.trim()).filter(Boolean))}/></section><section><button className="danger wide" onClick={()=>remove(edge.label||edge.id)}><Trash2 size={15}/> Eliminar conexión</button></section></aside>;
  }
  if (selected.type === 'event') {
    const item=project.events.find(current=>current.id===selected.id)!;const edit=<K extends keyof typeof item>(key:K,value:typeof item[K])=>commit('Editar acontecimiento',draft=>{draft.events.find(current=>current.id===item.id)![key]=value});
    return <aside className="inspector"><header><small>ACONTECIMIENTO</small><h2>{item.title}</h2></header><section><Field label="Título" value={item.title} onCommit={value=>edit('title',value)}/><Field label="Subtítulo" value={item.subtitle} onCommit={value=>edit('subtitle',value)}/><Select label="Tipo" value={item.kind} options={project.catalogs.eventKinds.map(option=>[option.id,option.label])} onChange={value=>edit('kind',value)}/><label className="field"><span>Resumen</span><textarea key={item.summary} defaultValue={item.summary} onBlur={event=>edit('summary',event.target.value)}/></label></section><section><div className="two"><Field label="X" type="number" value={item.x} onCommit={value=>edit('x',number(value,item.x))}/><Field label="Y" type="number" value={item.y} onCommit={value=>edit('y',number(value,item.y))}/><Field label="Longitud" type="number" value={item.width} onCommit={value=>edit('width',number(value,item.width))}/><Field label="Grosor" type="number" value={item.lineWidth} onCommit={value=>edit('lineWidth',number(value,item.lineWidth))}/></div><Field label="Color" type="color" value={item.color} onCommit={value=>edit('color',value)}/></section><section><button className="danger wide" onClick={()=>remove(item.title)}><Trash2 size={15}/> Eliminar acontecimiento</button></section></aside>;
  }
  if (selected.type === 'text') {
    const item=project.texts.find(current=>current.id===selected.id)!;const edit=<K extends keyof typeof item>(key:K,value:typeof item[K])=>commit('Editar texto',draft=>{draft.texts.find(current=>current.id===item.id)![key]=value});
    return <aside className="inspector"><header><small>TEXTO</small><h2>{item.text}</h2></header><section><label className="field"><span>Contenido</span><textarea key={item.text} defaultValue={item.text} onBlur={event=>edit('text',event.target.value)}/></label><div className="two"><Field label="Tamaño" type="number" value={item.fontSize} onCommit={value=>edit('fontSize',number(value,item.fontSize))}/><Field label="Peso" type="number" value={item.fontWeight} onCommit={value=>edit('fontWeight',number(value,item.fontWeight))}/></div><Field label="Color" type="color" value={item.color} onCommit={value=>edit('color',value)}/></section><section><button className="danger wide" onClick={()=>remove(item.text)}><Trash2 size={15}/> Eliminar texto</button></section></aside>;
  }
  if (selected.type === 'reference') {
    const item=project.references.find(current=>current.id===selected.id)!;const edit=<K extends keyof typeof item>(key:K,value:typeof item[K])=>commit('Editar imagen',draft=>{draft.references.find(current=>current.id===item.id)![key]=value});
    return <aside className="inspector"><header><small>IMAGEN</small><h2>{item.name}</h2></header><section><Field label="Nombre" value={item.name} onCommit={value=>edit('name',value)}/><Select label="Función" value={item.role} options={[['reference','Referencia'],['background','Fondo']]} onChange={value=>edit('role',value as typeof item.role)}/><div className="two"><Field label="X" type="number" value={item.x} onCommit={value=>edit('x',number(value,item.x))}/><Field label="Y" type="number" value={item.y} onCommit={value=>edit('y',number(value,item.y))}/><Field label="Anchura" type="number" value={item.width} onCommit={value=>edit('width',number(value,item.width))}/><Field label="Altura" type="number" value={item.height} onCommit={value=>edit('height',number(value,item.height))}/></div><Field label="Opacidad" type="number" value={item.opacity} min={0} max={1} step={.05} onCommit={value=>edit('opacity',number(value,item.opacity))}/><label className="check"><input type="checkbox" checked={item.lockAspect} onChange={event=>edit('lockAspect',event.target.checked)}/> Mantener proporción</label></section><section><button className="danger wide" onClick={()=>remove(item.name)}><Trash2 size={15}/> Eliminar imagen</button></section></aside>;
  }
  if (selected.type === 'area') {
    const item=project.areas.find(current=>current.id===selected.id)!;const edit=<K extends keyof typeof item>(key:K,value:typeof item[K])=>commit('Editar área',draft=>{draft.areas.find(current=>current.id===item.id)![key]=value});
    return <aside className="inspector"><header><small>ÁREA OPCIONAL</small><h2>{item.name}</h2></header><section><Field label="Nombre" value={item.name} onCommit={value=>edit('name',value)}/><div className="two"><Field label="X" type="number" value={item.x} onCommit={value=>edit('x',number(value,item.x))}/><Field label="Y" type="number" value={item.y} onCommit={value=>edit('y',number(value,item.y))}/><Field label="Anchura" type="number" value={item.width} onCommit={value=>edit('width',Math.max(20,number(value,item.width)))}/><Field label="Altura" type="number" value={item.height} onCommit={value=>edit('height',Math.max(20,number(value,item.height)))}/></div></section><section><h3>Fondo y contorno</h3><div className="two"><Field label="Relleno" type="color" value={item.fill} onCommit={value=>edit('fill',value)}/><Field label="Opacidad" type="number" value={item.fillOpacity} min={0} max={1} step={.01} onCommit={value=>edit('fillOpacity',number(value,item.fillOpacity))}/><Field label="Borde" type="color" value={item.stroke} onCommit={value=>edit('stroke',value)}/><Field label="Grosor" type="number" value={item.strokeWidth} min={0} step={.5} onCommit={value=>edit('strokeWidth',number(value,item.strokeWidth))}/></div><Field label="Radio de esquina" type="number" value={item.radius} min={0} onCommit={value=>edit('radius',number(value,item.radius))}/></section><section><button className="danger wide" onClick={()=>remove(item.name)}><Trash2 size={15}/> Eliminar área</button></section></aside>;
  }
  return <aside className="inspector"><header><small>OBJETO</small><h2>Sin datos</h2></header></aside>;
}
