import { useEffect, useRef, useState } from 'react';
import { ImagePlus, Plus, Trash2 } from 'lucide-react';
import { useEditorStore } from '../store/editorStore';
import { uid, type AtlasProject } from '../model/project';

type Option=[string,string];
function Field({label,value,type='text',onCommit,min,max,step,help}:{label:string;value:string|number;type?:string;onCommit:(value:string)=>void;min?:number;max?:number;step?:number;help?:string}){return <label className="field" title={help}><span>{label}{help&&<i className="help-dot">?</i>}</span><input key={`${label}-${value}`} type={type} defaultValue={value} min={min} max={max} step={step} onBlur={e=>onCommit(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/></label>}
function Textarea({label,value,onCommit,help}:{label:string;value:string;onCommit:(value:string)=>void;help?:string}){return <label className="field" title={help}><span>{label}{help&&<i className="help-dot">?</i>}</span><textarea key={`${label}-${value}`} defaultValue={value} onBlur={e=>onCommit(e.target.value)}/></label>}
function Select({label,value,options,onChange,help}:{label:string;value:string;options:Option[];onChange:(value:string)=>void;help?:string}){return <label className="field" title={help}><span>{label}{help&&<i className="help-dot">?</i>}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
const num=(value:string,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const scalar=(value:string):number|string|null=>value.trim()===''?null:Number.isFinite(Number(value))?Number(value):value;
const sortOptions=(options:Option[])=>options.sort((a,b)=>a[1].localeCompare(b[1],'es',{sensitivity:'base'}));
const descriptor=(node:{title:string;subtitle:string;visibleValue:string})=>[node.title,node.subtitle,node.visibleValue].filter(Boolean).join(' — ');

function Tabs({active,onChange,items}:{active:string;onChange:(tab:string)=>void;items:Option[]}){return <nav className="inspector-tabs">{items.map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>onChange(id)}>{label}</button>)}</nav>}

export function Inspector():React.JSX.Element{
  const project=useEditorStore(s=>s.project),selection=useEditorStore(s=>s.selection),update=useEditorStore(s=>s.updateProject),deleteSelection=useEditorStore(s=>s.deleteSelection),setSelection=useEditorStore(s=>s.setSelection);
  const [tab,setTab]=useState('content'),[newTarget,setNewTarget]=useState(''),iconInput=useRef<HTMLInputElement>(null);
  const selected=selection[0];useEffect(()=>{setTab('content');setNewTarget('')},[selected?.type,selected?.id]);
  const commit=(label:string,recipe:(draft:AtlasProject)=>void)=>update(label,recipe),remove=(name:string)=>confirm(`¿Eliminar «${name}»? La operación se podrá deshacer.`)&&deleteSelection();
  if(selection.length>1)return <aside className="inspector"><header><small>SELECCIÓN MÚLTIPLE</small><h2>{selection.length} objetos</h2></header><section><p className="muted">La selección rectangular y Mayús permiten mover o eliminar objetos como grupo.</p><button className="danger wide" onClick={()=>confirm(`¿Eliminar ${selection.length} objetos?`)&&deleteSelection()}><Trash2 size={15}/> Eliminar selección</button></section></aside>;
  if(!selected)return <aside className="inspector"><header><small>INSPECTOR</small><h2>Lienzo listo</h2></header><section><p className="muted">El proyecto puede permanecer completamente libre. Añade ejes o áreas sólo cuando aporten coordenadas útiles.</p><dl className="stats"><div><dt>Entidades</dt><dd>{project.nodes.length}</dd></div><div><dt>Conexiones</dt><dd>{project.edges.length}</dd></div><div><dt>Áreas</dt><dd>{project.areas.length}</dd></div><div><dt>Referencias</dt><dd>{project.references.length}</dd></div></dl></section></aside>;
  const nodeOptions=sortOptions(project.nodes.map(node=>[node.id,descriptor(node)]));

  if(selected.type==='node'){
    const node=project.nodes.find(x=>x.id===selected.id)!;const edit=<K extends keyof typeof node>(key:K,value:typeof node[K])=>commit('Editar entidad',draft=>{draft.nodes.find(x=>x.id===node.id)![key]=value});
    const editPlacement=<K extends keyof typeof node.placement>(key:K,value:typeof node.placement[K])=>commit('Editar coordenadas semánticas',draft=>{draft.nodes.find(x=>x.id===node.id)!.placement[key]=value});
    const editDetail=(key:string,value:string)=>commit('Editar ficha',draft=>{draft.nodes.find(x=>x.id===node.id)!.details[key]=value});
    const loadIcon=(file:File)=>{const reader=new FileReader();reader.onload=()=>edit('iconDataUrl',String(reader.result));reader.readAsDataURL(file)};
    const createRelation=()=>{if(!newTarget||newTarget===node.id)return;const id=uid('edge');commit('Crear relación',draft=>draft.edges.push({id,sourceId:node.id,targetId:newTarget,label:'',kind:draft.catalogs.edgeKinds[0]?.id??'connection',role:draft.catalogs.edgeRoles[0]?.id??'primary',strength:80,confidence:draft.catalogs.confidences[1]?.id??'medium',note:'',route:'curve',directed:true,color:'#475569',colors:[],width:3,dash:'',opacity:1,waypoints:[],layerId:draft.activeLayerId}));setSelection([{type:'edge',id}])};
    const relations=project.edges.filter(e=>e.sourceId===node.id||e.targetId===node.id).sort((a,b)=>descriptor(project.nodes.find(n=>n.id===(a.sourceId===node.id?a.targetId:a.sourceId))!).localeCompare(descriptor(project.nodes.find(n=>n.id===(b.sourceId===node.id?b.targetId:b.sourceId))!),'es'));
    return <aside className="inspector"><header><small>ENTIDAD</small><h2>{node.title}</h2></header><Tabs active={tab} onChange={setTab} items={[['content','Ficha'],['position','Coordenadas'],['style','Aspecto'],['relations','Relaciones'],['evidence','Evidencia']]}/>
      {tab==='content'&&<section><Field label="Título" value={node.title} onCommit={v=>edit('title',v)}/><Field label="Subtítulo" value={node.subtitle} onCommit={v=>edit('subtitle',v)}/><Field label="Valor visible" value={node.visibleValue} help="Tercer rótulo opcional bajo la entidad: fecha, magnitud, código o cualquier dato breve." onCommit={v=>edit('visibleValue',v)}/><div className="two"><Select label="Tipo" value={node.type} options={sortOptions(project.catalogs.nodeTypes.map(x=>[x.id,x.label]))} onChange={v=>edit('type',v)}/><Select label="Estado" value={node.status} options={sortOptions(project.catalogs.statuses.map(x=>[x.id,x.label]))} onChange={v=>edit('status',v)}/></div><Textarea label="Resumen" value={node.summary} onCommit={v=>edit('summary',v)}/><Textarea label="Descripción ampliada" value={node.details.overview??''} onCommit={v=>editDetail('overview',v)}/></section>}
      {tab==='position'&&<section><Select label="Modo de colocación" value={node.placement.mode} options={[['free','Libre (X/Y del lienzo)'],['semantic','Semántica (área + ejes)']]} help="En modo semántico, redimensionar el área o cambiar la escala recoloca la entidad automáticamente." onChange={v=>editPlacement('mode',v as typeof node.placement.mode)}/>{node.placement.mode==='semantic'&&<><Select label="Área de coordenadas" value={node.placement.areaId??''} options={[['','Lienzo completo'],...sortOptions(project.areas.map(x=>[x.id,x.name]))]} onChange={v=>{editPlacement('areaId',v||null);if(v&&!node.areaIds.includes(v))edit('areaIds',[...node.areaIds,v])}}/><div className="two"><Field label={`Valor X${project.board.axes.x.label?` · ${project.board.axes.x.label}`:''}`} value={node.placement.xValue??''} onCommit={v=>editPlacement('xValue',scalar(v))}/><Field label={`Valor Y${project.board.axes.y.label?` · ${project.board.axes.y.label}`:''}`} value={node.placement.yValue??''} onCommit={v=>editPlacement('yValue',scalar(v))}/><Field label="Corrección X" type="number" value={node.placement.offsetX} onCommit={v=>editPlacement('offsetX',num(v))}/><Field label="Corrección Y" type="number" value={node.placement.offsetY} onCommit={v=>editPlacement('offsetY',num(v))}/></div><h3>Duración / histograma</h3><div className="two"><Field label="Inicio" type="number" value={node.placement.durationStart??''} onCommit={v=>editPlacement('durationStart',v===''?null:num(v))}/><Field label="Final" type="number" value={node.placement.durationEnd??''} onCommit={v=>editPlacement('durationEnd',v===''?null:num(v))}/><Field label="Anchura temporal" type="number" min={.2} step={.2} value={node.placement.durationWidth} onCommit={v=>editPlacement('durationWidth',Math.max(.2,num(v,4)))}/></div></>}{node.placement.mode==='free'&&<div className="two"><Field label="X" type="number" value={node.x} onCommit={v=>edit('x',num(v,node.x))}/><Field label="Y" type="number" value={node.y} onCommit={v=>edit('y',num(v,node.y))}/></div>}<div className="two"><Field label="Anchura" type="number" min={20} value={node.width} onCommit={v=>edit('width',Math.max(20,num(v,node.width)))}/><Field label="Altura" type="number" min={20} value={node.height} onCommit={v=>edit('height',Math.max(20,num(v,node.height)))}/></div><label className="check"><input type="checkbox" checked={node.placement.avoidOverlap} onChange={e=>editPlacement('avoidOverlap',e.target.checked)}/> Evitar solapamientos al recalcular</label></section>}
      {tab==='style'&&<section><Select label="Forma" value={node.shape} options={[['sphere','Esfera'],['circle','Círculo'],['rounded','Rectángulo redondeado'],['rectangle','Rectángulo'],['diamond','Rombo'],['pill','Cápsula']]} onChange={v=>edit('shape',v as typeof node.shape)}/><label className="check"><input type="checkbox" checked={node.containerVisible} onChange={e=>edit('containerVisible',e.target.checked)}/> Mostrar cajetín o contenedor</label><p className="muted">Si lo desactivas, el SVG sustituye por completo al cajetín; los tres rótulos permanecen debajo.</p><div className="two"><Field label="Relleno" type="color" value={node.fill} onCommit={v=>edit('fill',v)}/><Field label="Borde" type="color" value={node.stroke} onCommit={v=>edit('stroke',v)}/><Field label="Grosor" type="number" value={node.strokeWidth} min={0} step={.5} onCommit={v=>edit('strokeWidth',num(v))}/><Field label="Opacidad" type="number" value={node.opacity} min={0} max={1} step={.05} onCommit={v=>edit('opacity',num(v,1))}/></div><h3>Icono SVG</h3><button className="wide" onClick={()=>iconInput.current?.click()}><ImagePlus size={15}/> Cargar SVG o imagen</button><input ref={iconInput} hidden type="file" accept="image/*,.svg" onChange={e=>{const file=e.target.files?.[0];if(file)loadIcon(file);e.target.value=''}}/><div className="two"><Field label="Escala del icono" type="number" min={.1} max={4} step={.05} value={node.iconScale} onCommit={v=>edit('iconScale',num(v,1))}/><Field label="Fondo del icono" type="color" value={node.iconBackground||'#ffffff'} onCommit={v=>edit('iconBackground',v)}/></div><label className="check"><input type="checkbox" checked={node.iconInvert??false} onChange={e=>edit('iconInvert',e.target.checked)}/> Invertir colores del icono</label>{node.iconDataUrl&&<button className="danger wide" onClick={()=>confirm('¿Quitar el icono de esta entidad?')&&edit('iconDataUrl',undefined)}>Quitar icono</button>}</section>}
      {tab==='relations'&&<section>{relations.map(edge=>{const other=project.nodes.find(n=>n.id===(edge.sourceId===node.id?edge.targetId:edge.sourceId));return <button className="relation-item" key={edge.id} onClick={()=>setSelection([{type:'edge',id:edge.id}])}><span>{edge.sourceId===node.id?'→':'←'} {other?descriptor(other):'Entidad ausente'}</span><small>{edge.role} · {edge.kind}</small></button>})}<Select label="Nuevo destino" value={newTarget} options={[['','Seleccionar…'],...nodeOptions.filter(([id])=>id!==node.id)]} onChange={setNewTarget}/><button className="wide" disabled={!newTarget} onClick={createRelation}><Plus size={14}/> Crear relación de salida</button></section>}
      {tab==='evidence'&&<section><Textarea label="Historia y contexto" value={node.details.history??''} onCommit={v=>editDetail('history',v)}/><Textarea label="Doctrinas, propiedades o funcionamiento" value={node.details.beliefs??''} onCommit={v=>editDetail('beliefs',v)}/><Textarea label="Evidencia y grado de certeza" value={node.details.evidence??''} onCommit={v=>editDetail('evidence',v)}/><Textarea label="Bibliografía y fuentes" value={node.details.bibliography??''} onCommit={v=>editDetail('bibliography',v)}/><Textarea label="Notas editoriales" value={node.details.notes??''} onCommit={v=>editDetail('notes',v)}/></section>}
      <section><button className="danger wide" onClick={()=>remove(node.title)}><Trash2 size={15}/> Eliminar entidad</button></section></aside>;
  }

  if(selected.type==='edge'){
    const edge=project.edges.find(x=>x.id===selected.id)!;const edit=<K extends keyof typeof edge>(key:K,value:typeof edge[K])=>commit('Editar conexión',draft=>{draft.edges.find(x=>x.id===edge.id)![key]=value});
    return <aside className="inspector"><header><small>CONEXIÓN</small><h2>{edge.label||'Sin etiqueta'}</h2></header><Tabs active={tab} onChange={setTab} items={[['content','Relación'],['route','Recorrido'],['style','Trazo']]}/>{tab==='content'&&<section><Field label="Etiqueta" value={edge.label} onCommit={v=>edit('label',v)}/><Select label="Origen" value={edge.sourceId} options={nodeOptions} onChange={v=>edit('sourceId',v)}/><Select label="Destino" value={edge.targetId} options={nodeOptions} onChange={v=>edit('targetId',v)}/><div className="two"><Select label="Tipo" value={edge.kind} options={sortOptions(project.catalogs.edgeKinds.map(x=>[x.id,x.label]))} onChange={v=>edit('kind',v)}/><Select label="Rol" value={edge.role} options={sortOptions(project.catalogs.edgeRoles.map(x=>[x.id,x.label]))} onChange={v=>edit('role',v)}/><Select label="Confianza" value={edge.confidence} options={sortOptions(project.catalogs.confidences.map(x=>[x.id,x.label]))} onChange={v=>edit('confidence',v)}/><Field label="Fuerza %" type="number" min={1} max={100} value={edge.strength} onCommit={v=>edit('strength',Math.max(1,Math.min(100,num(v,60))))}/></div><label className="check"><input type="checkbox" checked={edge.directed} onChange={e=>edit('directed',e.target.checked)}/> Relación dirigida</label><Textarea label="Nota documental" value={edge.note} onCommit={v=>edit('note',v)}/></section>}{tab==='route'&&<section><Select label="Recorrido" value={edge.route} options={[['straight','Recta'],['orthogonal','Ortogonal'],['curve','Curva']]} onChange={v=>edit('route',v as typeof edge.route)}/><Textarea label="Puntos de paso (X,Y por línea)" value={edge.waypoints.map(p=>`${p.x}, ${p.y}`).join('\n')} help="Permite dirigir manualmente el recorrido sin soltar los extremos de sus entidades." onCommit={v=>edit('waypoints',v.split(/\r?\n/).map(line=>line.split(',').map(Number)).filter(pair=>pair.length===2&&pair.every(Number.isFinite)).map(([x,y])=>({x,y})))}/></section>}{tab==='style'&&<section><div className="two"><Field label="Color" type="color" value={edge.color} onCommit={v=>edit('color',v)}/><Field label="Grosor" type="number" min={.2} step={.2} value={edge.width} onCommit={v=>edit('width',Math.max(.2,num(v,3)))}/><Field label="Opacidad" type="number" min={0} max={1} step={.05} value={edge.opacity} onCommit={v=>edit('opacity',num(v,1))}/></div><Field label="Patrón discontinuo SVG" value={edge.dash} help="Ejemplos: vacío = continua; 8 6 = guiones; 2 5 = puntos." onCommit={v=>edit('dash',v)}/><Field label="Degradado (colores separados por coma)" value={edge.colors.join(', ')} help="La línea atraviesa todos los colores indicados en orden." onCommit={v=>edit('colors',v.split(',').map(x=>x.trim()).filter(Boolean))}/></section>}<section><button className="danger wide" onClick={()=>remove(edge.label||edge.id)}><Trash2 size={15}/> Eliminar conexión</button></section></aside>;
  }

  if(selected.type==='area'){
    const area=project.areas.find(x=>x.id===selected.id)!;const edit=<K extends keyof typeof area>(key:K,value:typeof area[K])=>commit('Editar área',draft=>{draft.areas.find(x=>x.id===area.id)![key]=value}),pad=(key:keyof typeof area.padding,value:number)=>commit('Editar márgenes',draft=>{draft.areas.find(x=>x.id===area.id)!.padding[key]=value});
    return <aside className="inspector"><header><small>ÁREA SEMÁNTICA</small><h2>{area.name}</h2></header><Tabs active={tab} onChange={setTab} items={[['content','Geometría'],['position','Ejes'],['style','Aspecto']]}/>{tab==='content'&&<section><Field label="Nombre" value={area.name} onCommit={v=>edit('name',v)}/><div className="two"><Field label="X" type="number" value={area.x} onCommit={v=>edit('x',num(v))}/><Field label="Y" type="number" value={area.y} onCommit={v=>edit('y',num(v))}/><Field label="Anchura" type="number" min={80} value={area.width} onCommit={v=>edit('width',Math.max(80,num(v)))}/><Field label="Altura" type="number" min={80} value={area.height} onCommit={v=>edit('height',Math.max(80,num(v)))}/></div><p className="muted">También puedes estirar cualquiera de sus ocho tiradores directamente en el lienzo.</p></section>}{tab==='position'&&<section><label className="check"><input type="checkbox" checked={area.axisX} onChange={e=>edit('axisX',e.target.checked)}/> Captar eje X del proyecto</label><label className="check"><input type="checkbox" checked={area.axisY} onChange={e=>edit('axisY',e.target.checked)}/> Captar eje Y del proyecto</label><h3>Márgenes interiores del eje</h3><div className="two"><Field label="Superior" type="number" min={0} value={area.padding.top} onCommit={v=>pad('top',Math.max(0,num(v)))}/><Field label="Derecho" type="number" min={0} value={area.padding.right} onCommit={v=>pad('right',Math.max(0,num(v)))}/><Field label="Inferior" type="number" min={0} value={area.padding.bottom} onCommit={v=>pad('bottom',Math.max(0,num(v)))}/><Field label="Izquierdo" type="number" min={0} value={area.padding.left} onCommit={v=>pad('left',Math.max(0,num(v)))}/></div></section>}{tab==='style'&&<section><div className="two"><Field label="Relleno" type="color" value={area.fill} onCommit={v=>edit('fill',v)}/><Field label="Opacidad" type="number" min={0} max={1} step={.01} value={area.fillOpacity} onCommit={v=>edit('fillOpacity',num(v))}/><Field label="Borde" type="color" value={area.stroke} onCommit={v=>edit('stroke',v)}/><Field label="Grosor" type="number" min={0} step={.5} value={area.strokeWidth} onCommit={v=>edit('strokeWidth',num(v))}/></div><Field label="Radio de esquina" type="number" min={0} value={area.radius} onCommit={v=>edit('radius',Math.max(0,num(v)))}/></section>}<section><button className="danger wide" onClick={()=>remove(area.name)}><Trash2 size={15}/> Eliminar área</button></section></aside>;
  }

  if(selected.type==='event'){
    const item=project.events.find(x=>x.id===selected.id)!;const edit=<K extends keyof typeof item>(key:K,value:typeof item[K])=>commit('Editar acontecimiento',draft=>{draft.events.find(x=>x.id===item.id)![key]=value});
    return <aside className="inspector"><header><small>ACONTECIMIENTO</small><h2>{item.title}</h2></header><Tabs active={tab} onChange={setTab} items={[['content','Ficha'],['position','Alcance'],['style','Trazo']]}/>{tab==='content'&&<section><Field label="Título" value={item.title} onCommit={v=>edit('title',v)}/><Field label="Subtítulo" value={item.subtitle} onCommit={v=>edit('subtitle',v)}/><Select label="Tipo" value={item.kind} options={sortOptions(project.catalogs.eventKinds.map(x=>[x.id,x.label]))} onChange={v=>edit('kind',v)}/><Textarea label="Resumen" value={item.summary} onCommit={v=>edit('summary',v)}/></section>}{tab==='position'&&<section><Select label="Alcance" value={item.scope} options={[['free','Libre'],['areas','Áreas'],['entities','Entidades concretas'],['mixed','Áreas y entidades']]} onChange={v=>edit('scope',v as typeof item.scope)}/><div className="two"><Field label="Valor del eje" value={item.axisValue??''} onCommit={v=>edit('axisValue',scalar(v))}/><Field label="Valor final" value={item.endValue??''} onCommit={v=>edit('endValue',scalar(v))}/></div><h3>Entidades afectadas</h3><div className="check-list">{nodeOptions.map(([id,label])=><label key={id}><input type="checkbox" checked={item.entityIds.includes(id)} onChange={e=>edit('entityIds',e.target.checked?[...item.entityIds,id]:item.entityIds.filter(x=>x!==id))}/>{label}</label>)}</div></section>}{tab==='style'&&<section><div className="two"><Field label="X" type="number" value={item.x} onCommit={v=>edit('x',num(v))}/><Field label="Y" type="number" value={item.y} onCommit={v=>edit('y',num(v))}/><Field label="Longitud" type="number" value={item.width} onCommit={v=>edit('width',num(v))}/><Field label="Grosor" type="number" value={item.lineWidth} onCommit={v=>edit('lineWidth',num(v))}/></div><Field label="Color" type="color" value={item.color} onCommit={v=>edit('color',v)}/><Field label="Patrón SVG" value={item.dash} onCommit={v=>edit('dash',v)}/></section>}<section><button className="danger wide" onClick={()=>remove(item.title)}><Trash2 size={15}/> Eliminar acontecimiento</button></section></aside>;
  }

  const collection=selected.type==='text'?project.texts:project.references,item=collection.find(x=>x.id===selected.id) as any;const editAny=(key:string,value:any)=>commit('Editar objeto',draft=>{const list=selected.type==='text'?draft.texts:draft.references;(list.find(x=>x.id===selected.id) as any)[key]=value});
  return <aside className="inspector"><header><small>{selected.type==='text'?'TEXTO':'IMAGEN'}</small><h2>{item.text??item.name}</h2></header><section>{selected.type==='text'?<><Textarea label="Contenido" value={item.text} onCommit={v=>editAny('text',v)}/><Field label="Tamaño" type="number" value={item.fontSize} onCommit={v=>editAny('fontSize',num(v))}/><Field label="Color" type="color" value={item.color} onCommit={v=>editAny('color',v)}/></>:<><Field label="Nombre" value={item.name} onCommit={v=>editAny('name',v)}/><div className="two"><Field label="X" type="number" value={item.x} onCommit={v=>editAny('x',num(v))}/><Field label="Y" type="number" value={item.y} onCommit={v=>editAny('y',num(v))}/><Field label="Anchura" type="number" value={item.width} onCommit={v=>editAny('width',num(v))}/><Field label="Altura" type="number" value={item.height} onCommit={v=>editAny('height',num(v))}/></div><Field label="Opacidad" type="number" min={0} max={1} step={.05} value={item.opacity} onCommit={v=>editAny('opacity',num(v))}/></>}</section><section><button className="danger wide" onClick={()=>remove(item.text??item.name)}><Trash2 size={15}/> Eliminar</button></section></aside>;
}
