import { useRef } from 'react';
import { ArrowDown, ArrowUp, Eye, EyeOff, ImagePlus, Layers3, Lock, Plus, Trash2, Unlock, X } from 'lucide-react';
import { useEditorStore } from '../store/editorStore';
import { defaultAxis, uid, type AtlasProject, type AxisDefinition, type Catalogs } from '../model/project';
import { ColorField } from './ColorField';

const n=(value:string,fallback:number)=>Number.isFinite(Number(value))?Number(value):fallback;

function AxisEditor({orientation,axis,commit}:{orientation:'x'|'y';axis:AxisDefinition;commit:(label:string,recipe:(draft:AtlasProject)=>void)=>void}){
  const edit=<K extends keyof AxisDefinition>(key:K,value:AxisDefinition[K])=>commit(`Configurar eje ${orientation.toUpperCase()}`,draft=>{draft.board.axes[orientation][key]=value});
  const editCategory=(index:number,key:'label'|'weight',value:string|number)=>commit('Editar categoría',draft=>{(draft.board.axes[orientation].categories[index] as any)[key]=value});
  const moveCategory=(index:number,direction:number)=>commit('Reordenar categorías',draft=>{const list=draft.board.axes[orientation].categories,target=index+direction;if(target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]]});
  const editSegment=(index:number,key:'from'|'to'|'step'|'weight',value:number)=>commit('Editar tramo de eje',draft=>{draft.board.axes[orientation].segments[index][key]=value});
  const moveSegment=(index:number,direction:number)=>commit('Reordenar tramos',draft=>{const list=draft.board.axes[orientation].segments,target=index+direction;if(target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]]});
  return <section className="panel-section axis-editor"><h3>Eje general {orientation.toUpperCase()}</h3><div className="two"><label className="field"><span>Tipo</span><select value={axis.mode} onChange={e=>edit('mode',e.target.value as AxisDefinition['mode'])}><option value="none">Sin eje</option><option value="timeline">Cronológico</option><option value="numeric">Numérico</option><option value="categories">Categorías libres</option></select></label><label className="check standalone"><input type="checkbox" checked={axis.visible} onChange={e=>edit('visible',e.target.checked)}/> Mostrar eje general</label></div><label className="field"><span>Nombre o unidad</span><input value={axis.label} onChange={e=>edit('label',e.target.value)}/></label>
    {axis.mode!=='none'&&<label className="check"><input type="checkbox" checked={axis.reverse} onChange={e=>edit('reverse',e.target.checked)}/> Invertir dirección visual</label>}
    {(axis.mode==='numeric'||axis.mode==='timeline')&&<><div className="two"><label className="field"><span>Mínimo total</span><input type="number" defaultValue={axis.min} onBlur={e=>edit('min',n(e.target.value,axis.min))}/></label><label className="field"><span>Máximo total</span><input type="number" defaultValue={axis.max} onBlur={e=>edit('max',n(e.target.value,axis.max))}/></label><label className="field"><span>Paso si no hay tramos</span><input type="number" min=".000001" defaultValue={axis.step} onBlur={e=>edit('step',Math.max(.000001,n(e.target.value,axis.step)))}/></label></div><div className="section-heading"><h3>Tramos de escala</h3><button className="small" onClick={()=>commit('Añadir tramo',draft=>{const target=draft.board.axes[orientation],last=target.segments.at(-1),from=last?.to??target.min,to=target.max;target.segments.push({id:uid('segment'),from,to,step:target.step,weight:1})})}><Plus size={14}/> Tramo</button></div><p className="muted">Cada tramo define rango, paso de marcas y espacio visual relativo. Sin tramos se usa una escala lineal.</p>{axis.segments.map((segment,index)=><div className="axis-row segment-row" key={segment.id}><input type="number" defaultValue={segment.from} title="Desde" onBlur={e=>editSegment(index,'from',n(e.target.value,segment.from))}/><input type="number" defaultValue={segment.to} title="Hasta" onBlur={e=>editSegment(index,'to',n(e.target.value,segment.to))}/><input type="number" min=".000001" defaultValue={segment.step} title="Paso" onBlur={e=>editSegment(index,'step',Math.max(.000001,n(e.target.value,segment.step)))}/><input type="number" min=".01" step=".1" defaultValue={segment.weight} title="Tamaño relativo" onBlur={e=>editSegment(index,'weight',Math.max(.01,n(e.target.value,segment.weight)))}/><button className="icon" disabled={!index} title="Subir" onClick={()=>moveSegment(index,-1)}><ArrowUp size={13}/></button><button className="icon" disabled={index===axis.segments.length-1} title="Bajar" onClick={()=>moveSegment(index,1)}><ArrowDown size={13}/></button><button className="icon danger" title="Eliminar tramo" onClick={()=>confirm('¿Eliminar este tramo de escala?')&&commit('Eliminar tramo',draft=>draft.board.axes[orientation].segments.splice(index,1))}><Trash2 size={13}/></button></div>)}</>}
    {axis.mode==='categories'&&<><div className="section-heading"><h3>Categorías y tamaños</h3><button className="small" onClick={()=>commit('Añadir categoría',draft=>draft.board.axes[orientation].categories.push({id:uid('category'),label:'Nueva categoría',weight:1}))}><Plus size={14}/> Categoría</button></div><p className="muted">Puedes escribir cualquier categoría, asignarle una anchura/altura relativa y reordenarla.</p>{axis.categories.map((category,index)=><div className="axis-row category-row" key={category.id}><input value={category.label} onChange={e=>editCategory(index,'label',e.target.value)}/><input type="number" min=".01" step=".1" value={category.weight} title="Tamaño relativo" onChange={e=>editCategory(index,'weight',Math.max(.01,n(e.target.value,category.weight)))}/><button className="icon" disabled={!index} title="Subir" onClick={()=>moveCategory(index,-1)}><ArrowUp size={13}/></button><button className="icon" disabled={index===axis.categories.length-1} title="Bajar" onClick={()=>moveCategory(index,1)}><ArrowDown size={13}/></button><button className="icon danger" title="Eliminar categoría" onClick={()=>confirm(`¿Eliminar «${category.label}»?`)&&commit('Eliminar categoría',draft=>draft.board.axes[orientation].categories.splice(index,1))}><Trash2 size={13}/></button></div>)}</>}
  </section>;
}

export function ProjectDialog({onClose}:{onClose:()=>void}):React.JSX.Element{
  const project=useEditorStore(s=>s.project),update=useEditorStore(s=>s.updateProject),referenceInput=useRef<HTMLInputElement>(null),commit=(label:string,recipe:(draft:AtlasProject)=>void)=>update(label,recipe);
  const editBoard=(key:keyof AtlasProject['board'],value:any)=>commit('Configurar lienzo',draft=>{(draft.board as any)[key]=value});
  const addReference=(file:File)=>{const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>commit('Añadir referencia',draft=>draft.references.push({id:uid('reference'),name:file.name,role:'reference',dataUrl:String(reader.result),x:120,y:120,width:image.naturalWidth||1200,height:image.naturalHeight||800,rotation:0,opacity:.35,visible:true,locked:false,lockAspect:true,layerId:draft.activeLayerId}));image.src=String(reader.result)};reader.readAsDataURL(file)};
  const catalog=(key:keyof Catalogs,title:string)=><section className="catalog-card"><h3>{title}</h3>{project.catalogs[key].map((item,index)=><div className="catalog-row" key={item.id}><input value={item.id} onChange={e=>commit('Editar catálogo',draft=>{draft.catalogs[key][index].id=e.target.value})}/><input value={item.label} onChange={e=>commit('Editar catálogo',draft=>{draft.catalogs[key][index].label=e.target.value})}/><button className="icon danger" title="Eliminar opción" onClick={()=>confirm(`¿Eliminar «${item.label}»?`)&&commit('Eliminar opción',draft=>draft.catalogs[key].splice(index,1))}><Trash2 size={14}/></button></div>)}<button className="small" onClick={()=>commit('Añadir opción',draft=>draft.catalogs[key].push({id:uid('option'),label:'Nueva opción'}))}><Plus size={14}/> Añadir</button></section>;
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="project-dialog"><header><div><small>CONFIGURACIÓN GENERAL</small><h2>Proyecto, lienzo y ejes</h2></div><button className="icon" onClick={onClose}><X size={19}/></button></header><div className="project-body"><div className="project-column">
    <section className="panel-section"><h3>Documento</h3><label className="field"><span>Título</span><input value={project.title} onChange={e=>commit('Renombrar proyecto',draft=>{draft.title=e.target.value})}/></label><label className="field"><span>Descripción</span><textarea value={project.description} onChange={e=>commit('Editar descripción',draft=>{draft.description=e.target.value})}/></label></section>
    <section className="panel-section"><h3>Lienzo</h3><div className="two"><label className="field"><span>Anchura</span><input type="number" value={project.board.width} onChange={e=>editBoard('width',Math.max(800,n(e.target.value,project.board.width)))}/></label><label className="field"><span>Altura</span><input type="number" value={project.board.height} onChange={e=>editBoard('height',Math.max(600,n(e.target.value,project.board.height)))}/></label><ColorField label="Fondo" value={project.board.background} onChange={v=>editBoard('background',v)}/><label className="field"><span>Opacidad del fondo</span><input type="number" min="0" max="1" step=".05" value={project.board.backgroundOpacity} onChange={e=>editBoard('backgroundOpacity',n(e.target.value,1))}/></label></div><div className="checks-inline"><label><input type="checkbox" checked={project.board.gridVisible} onChange={e=>editBoard('gridVisible',e.target.checked)}/> Cuadrícula</label><label><input type="checkbox" checked={project.board.snap} onChange={e=>editBoard('snap',e.target.checked)}/> Ajustar</label><label><input type="checkbox" checked={project.board.autoExpand} onChange={e=>editBoard('autoExpand',e.target.checked)}/> Expandir</label></div><div className="two"><label className="field"><span>Paso de cuadrícula</span><input type="number" value={project.board.gridSize} onChange={e=>editBoard('gridSize',Math.max(1,n(e.target.value,40)))}/></label><ColorField label="Color de cuadrícula" value={project.board.gridColor} onChange={v=>editBoard('gridColor',v)}/></div></section>
    <AxisEditor orientation="y" axis={project.board.axes.y} commit={commit}/><AxisEditor orientation="x" axis={project.board.axes.x} commit={commit}/>
  </div><div className="project-column">
    <section className="panel-section"><div className="section-heading"><h3><Layers3 size={16}/> Capas</h3><button className="small" onClick={()=>commit('Añadir capa',draft=>{const id=uid('layer');draft.layers.push({id,name:`Capa ${draft.layers.length+1}`,visible:true,locked:false,order:draft.layers.length});draft.activeLayerId=id})}><Plus size={14}/> Capa</button></div>{project.layers.slice().sort((a,b)=>a.order-b.order).map(layer=><div className={`layer-row ${project.activeLayerId===layer.id?'active':''}`} key={layer.id} onClick={()=>commit('Activar capa',draft=>{draft.activeLayerId=layer.id})}><input value={layer.name} onClick={e=>e.stopPropagation()} onChange={e=>commit('Renombrar capa',draft=>{draft.layers.find(x=>x.id===layer.id)!.name=e.target.value})}/><button className="icon" title="Mostrar u ocultar" onClick={e=>{e.stopPropagation();commit('Visibilidad de capa',draft=>{const item=draft.layers.find(x=>x.id===layer.id)!;item.visible=!item.visible})}}>{layer.visible?<Eye size={15}/>:<EyeOff size={15}/>}</button><button className="icon" title="Bloquear" onClick={e=>{e.stopPropagation();commit('Bloquear capa',draft=>{const item=draft.layers.find(x=>x.id===layer.id)!;item.locked=!item.locked})}}>{layer.locked?<Lock size={15}/>:<Unlock size={15}/>}</button><button className="icon danger" disabled={project.layers.length===1} title="Eliminar capa" onClick={e=>{e.stopPropagation();if(!confirm(`¿Eliminar «${layer.name}»? Sus objetos pasarán a otra capa.`))return;commit('Eliminar capa',draft=>{const fallback=draft.layers.find(x=>x.id!==layer.id)!;for(const list of [draft.areas,draft.nodes,draft.edges,draft.events,draft.texts,draft.references])for(const item of list)if(item.layerId===layer.id)item.layerId=fallback.id;draft.layers=draft.layers.filter(x=>x.id!==layer.id);draft.activeLayerId=fallback.id})}}><Trash2 size={14}/></button></div>)}</section>
    <section className="panel-section"><div className="section-heading"><h3>Áreas de coordenadas</h3><button className="small" onClick={()=>commit('Añadir área',draft=>draft.areas.push({id:uid('area'),name:'Nueva área',x:120,y:120,width:700,height:draft.board.height-240,fill:'#3b82f6',fillOpacity:.08,stroke:'#3b82f6',strokeWidth:2,radius:14,padding:{top:28,right:28,bottom:28,left:28},axisBindings:{x:{mode:'local-project',visible:false,axis:defaultAxis(false)},y:{mode:'project',visible:false,axis:defaultAxis(true)}},layerId:draft.activeLayerId}))}><Plus size={14}/> Área</button></div><p className="muted">Por defecto, X usa la escala del proyecto dentro del área y Y usa el eje general. Puedes cambiar cada combinación desde el inspector del área.</p>{project.areas.map(area=><div className="reference-row" key={area.id}><span>{area.name}</span><small>X: {area.axisBindings.x.mode} · Y: {area.axisBindings.y.mode}</small></div>)}</section>
    <section className="panel-section"><div className="section-heading"><h3>Referencias y fondos</h3><button className="small" onClick={()=>referenceInput.current?.click()}><ImagePlus size={14}/> Añadir</button></div>{project.references.map(item=><div className="reference-row" key={item.id}><span>{item.name}</span><small>{item.role==='background'?'Fondo':'Referencia'} · {Math.round(item.opacity*100)}%</small></div>)}<input ref={referenceInput} hidden type="file" accept="image/*,.svg" onChange={e=>{const file=e.target.files?.[0];if(file)addReference(file);e.target.value=''}}/></section>
  </div></div><div className="catalog-grid">{catalog('nodeTypes','Tipos de entidad')}{catalog('statuses','Estados')}{catalog('edgeKinds','Tipos de conexión')}{catalog('edgeRoles','Roles de conexión')}{catalog('confidences','Confianza')}{catalog('eventKinds','Tipos de acontecimiento')}</div></div></div>;
}
