import { useRef } from 'react';
import { Eye, EyeOff, ImagePlus, Layers3, Lock, Plus, Trash2, Unlock, X } from 'lucide-react';
import { useEditorStore } from '../store/editorStore';
import { uid, type AtlasProject, type Catalogs } from '../model/project';

const n = (value: string, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;

export function ProjectDialog({ onClose }: { onClose: () => void }): React.JSX.Element {
  const project = useEditorStore(state => state.project);
  const update = useEditorStore(state => state.updateProject);
  const referenceInput = useRef<HTMLInputElement>(null);
  const commit = (label: string, recipe: (draft: AtlasProject) => void) => update(label, recipe);
  const editBoard = (key: keyof AtlasProject['board'], value: AtlasProject['board'][keyof AtlasProject['board']]) => commit('Configurar lienzo', draft => { (draft.board as unknown as Record<string, unknown>)[key] = value; });
  const editAxis = (key: keyof AtlasProject['board']['axis'], value: AtlasProject['board']['axis'][keyof AtlasProject['board']['axis']]) => commit('Configurar eje', draft => { (draft.board.axis as unknown as Record<string, unknown>)[key] = value; });
  const addReference = (file: File) => {
    const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => commit('Añadir referencia', draft => { const id=uid('reference'), width=image.naturalWidth||1200,height=image.naturalHeight||800;draft.references.push({id,name:file.name,role:'reference',dataUrl:String(reader.result),x:120,y:120,width,height,rotation:0,opacity:.35,visible:true,locked:false,lockAspect:true,layerId:draft.activeLayerId}); }); image.src=String(reader.result); }; reader.readAsDataURL(file);
  };
  const catalog = (key: keyof Catalogs, title: string) => <section className="catalog-card"><h3>{title}</h3>{project.catalogs[key].map((item,index)=><div className="catalog-row" key={`${key}-${index}`}><input defaultValue={item.id} onBlur={event=>commit('Editar catálogo',draft=>{draft.catalogs[key][index].id=event.target.value.trim()||item.id})}/><input defaultValue={item.label} onBlur={event=>commit('Editar catálogo',draft=>{draft.catalogs[key][index].label=event.target.value.trim()||item.label})}/><button className="icon danger" title="Eliminar opción" onClick={()=>confirm(`¿Eliminar «${item.label}» del catálogo? Los objetos existentes conservarán el identificador.`)&&commit('Eliminar opción',draft=>{draft.catalogs[key].splice(index,1)})}><Trash2 size={14}/></button></div>)}<button className="small" onClick={()=>commit('Añadir opción',draft=>draft.catalogs[key].push({id:`option-${draft.catalogs[key].length+1}`,label:'Nueva opción'}))}><Plus size={14}/> Añadir opción</button></section>;

  return <div className="modal-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="project-dialog"><header><div><small>CONFIGURACIÓN GENERAL</small><h2>Proyecto y tablero</h2></div><button className="icon" onClick={onClose}><X size={19}/></button></header><div className="project-body">
    <div className="project-column"><section className="panel-section"><h3>Documento</h3><label className="field"><span>Título</span><input defaultValue={project.title} onBlur={event=>commit('Renombrar proyecto',draft=>{draft.title=event.target.value||'Proyecto sin título'})}/></label><label className="field"><span>Descripción</span><textarea defaultValue={project.description} onBlur={event=>commit('Editar descripción',draft=>{draft.description=event.target.value})}/></label></section>
      <section className="panel-section"><h3>Lienzo</h3><div className="two"><label className="field"><span>Anchura</span><input type="number" defaultValue={project.board.width} onBlur={event=>editBoard('width',Math.max(800,n(event.target.value,project.board.width)))}/></label><label className="field"><span>Altura</span><input type="number" defaultValue={project.board.height} onBlur={event=>editBoard('height',Math.max(600,n(event.target.value,project.board.height)))}/></label><label className="field"><span>Fondo</span><input type="color" value={project.board.background} onChange={event=>editBoard('background',event.target.value)}/></label><label className="field"><span>Opacidad</span><input type="number" min="0" max="1" step=".05" defaultValue={project.board.backgroundOpacity} onBlur={event=>editBoard('backgroundOpacity',n(event.target.value,1))}/></label></div><div className="checks-inline"><label><input type="checkbox" checked={project.board.gridVisible} onChange={event=>editBoard('gridVisible',event.target.checked)}/> Cuadrícula</label><label><input type="checkbox" checked={project.board.snap} onChange={event=>editBoard('snap',event.target.checked)}/> Ajustar</label><label><input type="checkbox" checked={project.board.autoExpand} onChange={event=>editBoard('autoExpand',event.target.checked)}/> Expandir</label></div><div className="two"><label className="field"><span>Paso de cuadrícula</span><input type="number" defaultValue={project.board.gridSize} onBlur={event=>editBoard('gridSize',Math.max(1,n(event.target.value,40)))}/></label><label className="field"><span>Color de cuadrícula</span><input type="color" value={project.board.gridColor} onChange={event=>editBoard('gridColor',event.target.value)}/></label></div></section>
      <section className="panel-section"><h3>Eje Y opcional</h3><div className="two"><label className="field"><span>Tipo</span><select value={project.board.axis.mode} onChange={event=>editAxis('mode',event.target.value as typeof project.board.axis.mode)}><option value="none">Sin eje</option><option value="timeline">Cronología</option><option value="numeric">Numérico</option><option value="categories">Categorías</option></select></label><label className="check standalone"><input type="checkbox" checked={project.board.axis.visible} onChange={event=>editAxis('visible',event.target.checked)}/> Visible</label><label className="field"><span>Mínimo</span><input type="number" defaultValue={project.board.axis.min} onBlur={event=>editAxis('min',n(event.target.value,0))}/></label><label className="field"><span>Máximo</span><input type="number" defaultValue={project.board.axis.max} onBlur={event=>editAxis('max',n(event.target.value,100))}/></label><label className="field"><span>Paso</span><input type="number" defaultValue={project.board.axis.step} onBlur={event=>editAxis('step',Math.max(.0001,n(event.target.value,10)))}/></label></div><label className="field"><span>Categorías, una por línea</span><textarea defaultValue={project.board.axis.categories.join('\n')} onBlur={event=>editAxis('categories',event.target.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))}/></label></section>
    </div>
    <div className="project-column"><section className="panel-section"><div className="section-heading"><h3><Layers3 size={16}/> Capas</h3><button className="small" onClick={()=>commit('Añadir capa',draft=>{const id=uid('layer');draft.layers.push({id,name:`Capa ${draft.layers.length+1}`,visible:true,locked:false,order:draft.layers.length});draft.activeLayerId=id})}><Plus size={14}/> Capa</button></div>{project.layers.sort((a,b)=>a.order-b.order).map(layer=><div className={`layer-row ${project.activeLayerId===layer.id?'active':''}`} key={layer.id} onClick={()=>commit('Activar capa',draft=>{draft.activeLayerId=layer.id})}><input value={layer.name} onClick={event=>event.stopPropagation()} onChange={event=>commit('Renombrar capa',draft=>{draft.layers.find(item=>item.id===layer.id)!.name=event.target.value})}/><button className="icon" title="Mostrar u ocultar" onClick={event=>{event.stopPropagation();commit('Cambiar visibilidad',draft=>{const item=draft.layers.find(current=>current.id===layer.id)!;item.visible=!item.visible})}}>{layer.visible?<Eye size={15}/>:<EyeOff size={15}/>}</button><button className="icon" title="Bloquear" onClick={event=>{event.stopPropagation();commit('Bloquear capa',draft=>{const item=draft.layers.find(current=>current.id===layer.id)!;item.locked=!item.locked})}}>{layer.locked?<Lock size={15}/>:<Unlock size={15}/>}</button><button className="icon danger" disabled={project.layers.length===1} title="Eliminar capa" onClick={event=>{event.stopPropagation();if(!confirm(`¿Eliminar la capa «${layer.name}»? Sus objetos pasarán a la primera capa.`))return;commit('Eliminar capa',draft=>{const fallback=draft.layers.find(item=>item.id!==layer.id)!;for(const collection of [draft.areas,draft.nodes,draft.edges,draft.events,draft.texts,draft.references])for(const item of collection)if(item.layerId===layer.id)item.layerId=fallback.id;draft.layers=draft.layers.filter(item=>item.id!==layer.id);draft.activeLayerId=fallback.id})}}><Trash2 size={14}/></button></div>)}</section>
      <section className="panel-section"><div className="section-heading"><h3>Referencias y fondos</h3><button className="small" onClick={()=>referenceInput.current?.click()}><ImagePlus size={14}/> Añadir</button></div>{project.references.length?project.references.map(item=><div className="reference-row" key={item.id}><span>{item.name}</span><small>{item.role==='background'?'Fondo':'Referencia'} · {Math.round(item.opacity*100)}%</small></div>):<p className="muted">Puedes añadir varias imágenes y redimensionarlas directamente en el lienzo.</p>}<input ref={referenceInput} hidden type="file" accept="image/*,.svg" onChange={event=>{const file=event.target.files?.[0];if(file)addReference(file);event.target.value='';}}/></section>
      <section className="panel-section"><div className="section-heading"><h3>Áreas opcionales</h3><button className="small" onClick={()=>commit('Añadir área',draft=>draft.areas.push({id:uid('area'),name:'Nueva área',x:120,y:120,width:700,height:draft.board.height-240,fill:'#3b82f6',fillOpacity:.08,stroke:'#3b82f6',strokeWidth:2,radius:14,layerId:draft.activeLayerId}))}><Plus size={14}/> Área</button></div><p className="muted">Las áreas son objetos opcionales; un proyecto puede permanecer completamente libre.</p>{project.areas.map(area=><div className="reference-row" key={area.id}><span>{area.name}</span><small>{area.width} × {area.height}</small></div>)}</section>
    </div>
  </div><div className="catalog-grid">{catalog('nodeTypes','Tipos de entidad')}{catalog('statuses','Estados')}{catalog('edgeKinds','Tipos de conexión')}{catalog('eventKinds','Tipos de acontecimiento')}</div></div></div>;
}
